### ISSUE TITLE
SilentAbort Exception error view

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#101]
Currently, a SilentAbortException is not handled very specific.

A SilentAbortException is a special Exception which stops code execution but doesn't show an error in GUI. 

If such SilentAbortException happens in a button action (= click), currently nothing was send to the client.

Current server will send an ErrorView with new property: silentAbort (boolean)

If ErrorView with silentAbort is set -> don't show a message and "cancel"

**Comment by maximilianweidenauer** [comment]
I've added, that silent-abort messages aren't shown on screen. Right now I don't really know what I should cancel when I'm receiving a silent-abort message.
