### ISSUE TITLE
Support setting screen parameters

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#102]
Currently, setting parameters for a work-screen only is possible during open command. With latest mobile server, it's also possible to set parameters with a new command:

`/api/setScreenParameter`

and also with close screen command:

`api/closeScreen`

The request should send a map with name:

`parameter`

e.g.

`/api/setScreenParameter`

REQUEST:
```
{
  "parameter" : {
    "offline.count" : 56,
    "offline.start" : true
  },
  "componentId" : "Con-CG",
  "clientId" : "5b57bec7-9534-4c48-bab9-a5a372f20038"
}
```

**Comment by maximilianweidenauer** [comment]
When using reactUI as lib it is now possible to add an array as property (like the custom screens) with a screen-name (array is also possible so multiple screens send the same parameters when opened or closed), and parameters. There is also a flag called onClose. When onClose is true, the screen-parameter are sent when the screen on closeScreen. When onClose is false or undefined, the parameters are sent on openScreen. The dev can send parameters anytime with the function sendScreenParameter of the server class.
