### ISSUE TITLE
Mouse Listener

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#115]
On the server we could implement a mouse clicked listener

**Comment by rjahn** [comment]
Implemented:

```
api/mousePressed
api/mouseClicked
api/mouseReleased
```

Request:

**MouseRequest**

clientId
componentId
button (text: Left, Right, Middle)
x (int)
y (int)

**MouseClickedRequest extends MouseRequest**

clickCount (int) (0/not set means 1)

**Comment by maximilianweidenauer** [comment]
When eventMouseClicked is true, send the requests

**Comment by rjahn** [comment]
check eventMouseReleased, eventMousePressed also
