### ISSUE TITLE
CellFormat Support

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#116]
The server currently doesn't support cellFormat

**Comment by rjahn** [comment]
Server now sends an optional **recordFormat** property. The property is a map with:

componentId as key
an object as value

The object has two properties: format, records

The format is a list of cellformats. The first element is always null.
The records property is a list of list (array of arrays). The number of format-records is the same as the number of data-records. The value of a format-record is the index of the cell-format list.

The cellformat syntax:

`background;foreground;font;image`

**Comment by rjahn** [comment]
example:

```
{
  "columnNames" : [ "ID", "FIRST_NAME", "LAST_NAME", "DOB", "REGNO" ],
  "records" : [ [ 0, "First", "Last", 644364000000, 109, null ], [ 1, "John", "Doe", 342226800000, 10, null ], [ 2, "Jane", "Doe", null, 19, null ], [ 3, null, "Sea", -313981200000, 51, null ], [ 4, "Tom", null, 949705200000, 63, null ] ],
  "name" : "dal.fetch",
  "isAllFetched" : true,
  "from" : 0,
  "dataProvider" : "JVxMobileDemo/CelPro-6S/cellProfileData#+",
  "selectedRow" : 4,
  "to" : 4,
  "recordFormat" : {
    "CelPro-6S_T_cellProfileData" : {
      "format" : [ null, "#404040;#FFFFFF;;", ";#FF0000;Default,1,12;", ";;;FontAwesome.plus-circle;color=#808080,16,16,false", ";#FFC800;;" ],
      "records" : [ [ 1, 0, 0, 0, 2 ], [ ], [ 1, 0, 0, 3, 0 ], [ 0, 3, 0, 0, 4 ], [ 1, 0, 3, 0, 2 ] ]
    }
  }
```

**Comment by rjahn** [comment]
and the table component:

```
{
    "id" : "T74",
    "name" : "CelPro-6S_T_cellProfileData",
    "className" : "Table",
    "columnNames" : [ "FIRST_NAME", "LAST_NAME", "DOB", "REGNO" ],
    "columnLabels" : [ "First Name", "Last Name", "Dob", "Regno" ],
    "maximumSize" : "800,600",
    "dataBook" : "JVxMobileDemo/CelPro-6S/cellProfileData#+",
    "parent" : "P73",
    "eventFocusGained" : true,
    "indexOf" : 0,
    "constraints" : "Center"
  }
```

**Comment by maximilianweidenauer** [comment]
Given there is a records array [0, 0, 0, 0, 0] the server will only send [].
When there is a records array [0, 0, 1, 1, 1] the server will send [0, 0, 1]
It is also possible that the index is -1, this means that there was an error while determining the format, if thats the case use 0 format (null)

**Comment by gimmixAT** [comment]
@rjahn   
Is the format mapping currently correctly sent? Because if I compare the render result in the swing application with the sent mapping there seems to be a slight mismatch. Currently in the sent data the ID column is formatted with a dark grey background on the odd rows but in the swing application that formatting is applied to the FIRST_NAME column.   
Also there seems to be an icon configured on the last three rows but in swing it only shows up on the third & fifth row.

**Comment by rjahn** [comment]
> Given there is a records array [0, 0, 0, 0, 0] the server will only send [].
> When there is a records array [0, 0, 1, 1, 1] the server will send [0, 0, 1]
> It is also possible that the index is -1, this means that there was an error while determining the format, if thats the case use 0 format (null)

correct. -1 means that there is a problem with format, but you should not apply any format (same as 0). but we want to see a difference between no format (0) and an exception (-1)

**Comment by rjahn** [comment]
> @rjahn
> Is the format mapping currently correctly sent? Because if I compare the render result in the swing application with the sent mapping there seems to be a slight mismatch. Currently in the sent data the ID column is formatted with a dark grey background on the odd rows but in the swing application that formatting is applied to the FIRST_NAME column.
> Also there seems to be an icon configured on the last three rows but in swing it only shows up on the third & fifth row.

You're right. The problem is that the fetch response returns all columns - also not visible columns. The table hides some columns. So there's a difference.... Have to take a look.

**Comment by rjahn** [comment]
should work now. I didn't recognize the column names of the table. Only "shown" column names should get a format.

**Comment by rjahn** [comment]
Current state?

**Comment by gimmixAT** [comment]
Support should be implemented and the testcase worked fine last time I checked

**Comment by maximilianweidenauer** [comment]
I've kept this ticket open, until I tested this feature with virtualscrolling. Virtualscrolling should work though... If there happens too be a problem later on, we'll just write a new ticket.
