### ISSUE TITLE
Table: autoResize property doesn't work as expected

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#122]
When the autoResize property is undefined or set to true, the table columns should use all width available and their size should be either set based on the column width property sent by the server (which is currently not supported) or the length of the longest data (checked in useLayoutEffect). When the table gets resized (eg. SplitPanel) the table and its columns adjusts its width to still use 100% of the width so that there is no scrollbar when getting smaller.
When autoResize is false, the columns always take their full width, they don't care if they overflow the table width, a scrollbar is available instead. When making the table smaller in a splitpanel, the columns are being "pushed out" if there is no more width available -> scrollbar. Also, when resizing columns smaller, the table shoudn't have 100% width = when the last column is resized smaller, there will be a gap between table container and table.

**Comment by maximilianweidenauer** [comment]
I think that in autoresize true/undefined works. But autoresize false currently only works in table which don't have virtualscrolling enabled. The table-columns will still only try to use 100% of the table's width and won't overflow. Also, when scrolling horizontally, the tablerow-tableheader alignment gets messed up.

**Comment by gimmixAT** [comment]
This might be fixed but relies on the sizing of the initially loaded values. So if larger values are loaded when scrolling down, they will be clipped with an ellipsis.

**Comment by maximilianweidenauer** [comment]
I will check it out tomorrow. But I guess this will be fine because we can't look into every every single datarow when there are a lot. So eventually it's always possible that there a larger values further down. I think in my useLayoutEffect where we check for the widths for the headers, I think I only check for the first 20 values

**Comment by gimmixAT** [comment]
Yup, I'll probably extend that check to use all currently loaded rows and that should give us a somewhat reliable estimate
