### ISSUE TITLE
More Application Frame Features

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#130]
The application frame should have more features, eg. save button, also the possibility to hide the buttons

**Comment by maximilianweidenauer** [comment]
also maybe a button to go back to welcomescreen/no screen opened, because now with preserve on reload when reloading you always go to the last opened screen and maybe you want to go the an empty "screen"

**Comment by maximilianweidenauer** [comment]
I'll add a save and a home button to the topbar.
The save command of the server needs to be updated and server needs to send a flag if these buttons should be visible or not. @rjahn could you already comment how this flag will be named so i can use it already?

**Comment by rjahn** [comment]
```
api/save
api/reload

```
should already work with current version in repo.

**Comment by maximilianweidenauer** [comment]
Home, Save, Rollback and Reload Buttons are now available and are shown based on application-settings
