### ISSUE TITLE
HTMLCellEditor Support

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#134]
When the HTMLCellEditor is ready, we need to support it, PrimeReact has a HTMLCellEditor

**Comment by rjahn** [comment]
What's the current state?

**Comment by gimmixAT** [comment]
The feature is basically implemented but will need some testing with more complex HTML constructs especially if react / swing interoperability is important.   
Right now the Swing HTML Editor uses a very archaic variant of HTML which we need to transform before and after editing it with the reactUI widget.
