### ISSUE TITLE
LinkedCellEditor: Columns are sent in the wrong order if there are more than 2 columns to be sent

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#142]
Last week Paul and Martin encountered a problem, where both mobile clients sent the columns and values in a wrong order. The LinkedCellEditor sent 3 columns/values. In the demos I currently don't have a screen with a LinkedCellEditor with 3 columns, so I don't really know what the problem is or how to reproduce the problem.

**Comment by rjahn** [comment]
DirectCellEditor screen now contains a new Editor which uses 4 columns
