### ISSUE TITLE
Different Application Frames

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#147]
We need a new application frame which has a menubar and a toolbar/sidebar/quick navigation bar (whatever). The menubar should look like a menu (menu with items) -> menu has a text and item has a text.

The sidebar/toolbar only shows text and icon. It should be placed left or right below the menubar....

It should be possible to show/hide menu/toolbar separately via application settings property.
It should be possible to define the application frame e.g. by applictionMetaData -> appframe: standard, corporate, modern, ...

**Comment by rjahn** [comment]
Properties in applicationSettings:

```
menuBar (boolean)
toolBar (boolean)
```

**Comment by rjahn** [comment]
Tool toolbar entries are now available via menuView -> toolBarEntries
(similar to entries, but no group name)

**Comment by maximilianweidenauer** [comment]
Is there a test already?

**Comment by rjahn** [comment]
As usual. features user.

**Comment by maximilianweidenauer** [comment]
The corporation application-frame should now work as expected
