### ISSUE TITLE
Table: Should have a bigger minimum size set, doesn't receive preferredSize

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#151]
While testing we encountered a table with no records in it, thus the table reported its height as ~60px... We should use a bigger minimum size for tables.

Also the table has a preferredSize set in the code but i don't receive it in the properties of the table.
![image](https://user-images.githubusercontent.com/66732863/126168155-e38ec59f-c0af-43ee-a933-b864f964b0ce.png)
![setpref](https://user-images.githubusercontent.com/66732863/126168351-caf2ece7-45f1-451c-af73-cfea11385420.png)

**Comment by rjahn** [comment]
don't calculate a "better" minimum size. The min size is the table-header height.... If it's not big enough, the user should set the correct size. We should support preferred height for tables, so if there's no record -> only header.
