### ISSUE TITLE
Home-Button always links to "/home" instead of potential welcome screen, always sends closeScreenRequest

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#156]
The home-button of the topbar always redirects the user to the "/home" url but if a welcome screen is set, the welcome screen should be opened. Also when redirected to home and pressing the home-button again, the closeScreenRequest is always sent, even if there is no screen opened. Also better tooltip position

**Comment by rjahn** [comment]
Latest Server implementation returns an optional response with the name **welcomeData**. The response currently contains the property: `homeScreen` It's a string and contains the full qualified class name of the "welcome screen".

If set, use this class for home navigation.

We also introduced a new optional property for openScreen request:

`className` (string)

The openScreen request usually opens a screen with the componentId from the menu entry. But it should be possible to open a screen by class name - in case of the welcome/home screen.

Last but not least, the genericScreenView response contains the **home (boolean)** property. If set, this screen is the home screen. But this doesn't mean that the screen was opened automatically. It's only an information.
