### ISSUE TITLE
eventFocusGained true is always sent

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#159]
The property eventFocusGained = true is always sent on editors and tables. Maybe on more components but haven't checked all of them. (Buttons, labels, icons, panels are fine)

**Comment by rjahn** [comment]
This is ok because the application has to know the current "controller". Be sure that you send the event if set.

**Comment by maximilianweidenauer** [comment]
eventFocusGained/eventFocusLost is now available for all input components
