### ISSUE TITLE
API to register/create custom screens

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#16]
Following use-cases:

1. User creates a custom "screen" with react and without Java

We need an API to support custom screen registration

2. User wants to use server-data (dataProvider) for a custom screen - created in react

We need an API (custom screen) to support re-using dataprovider and a high level data API as well

3. User re-uses the Java screen and needs a custom component in the screen

Component Placeholder support -> a panel will be added to the screen in Java code and a name will be set for the component. Also possible is a custom class. The custom class has a custom className...

In both cases, we need support for component replacement by componentId and/or class name (both together, because the class name is not unique, maybe)

We could check the [flutter implementation](https://github.com/sibvisions/flutterclient) to get an idea an to be compatible?

**Comment by Michael-Schober** [comment]
5321b1c21b980ad0f363823516dbbdbd77519051 first implementation
