### ISSUE TITLE
Table: when autoresize false stretch columns

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#160]
When autoresize is false and the whole width is NOT used by the columns stretch the columns to 100% first pick vaadin second react

![image](https://user-images.githubusercontent.com/66732863/126173905-8cfed5cb-bbd1-4de5-ae69-524d88c37895.png)
![image](https://user-images.githubusercontent.com/66732863/126174048-a15f6acf-438e-401d-8cff-d2c3d866e92d.png)

**Comment by gimmixAT** [comment]
mh this contradicts #122 a bit. Or should the table take 100% per default but should be manually resizable below that?

**Comment by maximilianweidenauer** [comment]
Yeah thats right! I misunderstood that first but the columns should take 100% and then you should be able to resize smaller and also bigger so that the columns are being pushed out ( thats already possible)
