### ISSUE TITLE
Label wraps text in component table

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#161]
In a specific screen, the label reports its size not correctly and wraps. Check internal ticketing for more info

**Comment by gimmixAT** [comment]
this is probably also fixed by https://github.com/sibvisions/reactUI/commit/466fdae3203575d34fdad70ce2c6b0721e666d0c

There was a similar break issue in the internal test app with numbered labels which is also gone and was caused by the browser internal floor on the width.
