### ISSUE TITLE
Changing Name, Image of Profile

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#170]
It should be possible to let the User change their name or image in the profile-menu. Currently this is only possible through the "user management" screen. The server could maybe handle it like change password? 
When changeProfileName/changeProfileImage = true, show a entry "change name"/"change image" in the profile-menu. And then show a popup to change the desired fields

**Comment by rjahn** [comment]
We won't implement this feature because it's server only.
