### ISSUE TITLE
Axis scale on x - y is wrong

### ISSUE THREAD

**Issue by mhandsteiner** [sibvisions/reactUI#176]
The scale on x and y axis should not have hard coded bounds or +1 -1...
Best is, to use the default automatic scaling. The y axis should be scaled from 0 to next round bounds.
The x axis should be scaled from previous round bounds to next round bounds.

![charts-xy-screenshot1](https://user-images.githubusercontent.com/43437457/132680588-74c06634-3cb6-4864-ac2d-6b3ad2225e88.PNG)
![charts-xy-screenshot2](https://user-images.githubusercontent.com/43437457/132680605-40e5b786-44a4-4091-b8bf-70ffd0dca03d.PNG)

![Charts1](https://user-images.githubusercontent.com/43437457/132682267-1b11fea3-ed98-4ffe-98ff-9f48de5ea3ba.png)
![Charts2](https://user-images.githubusercontent.com/43437457/132682297-af25a225-f36b-4ec6-b093-e364a0c86152.png)

**Comment by gimmixAT** [comment]
the charts should render properly now for larger values

**Comment by maximilianweidenauer** [comment]
Charts seem to be fine now, compared it with swing... I actually found a problem in swing:
![image](https://user-images.githubusercontent.com/66732863/133040892-1a0c2fe1-f1ad-4bb6-9c2e-5f41cb4e1a1d.png)
the ticks on the y-axis go all the way up to 500000% @mhandsteiner
