### ISSUE TITLE
Submenugroups aren't correctly displayed

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#179]
In VisionX it's possible that a menugroup has other menugroups in it... Currently the server sends the submenugroups like "abc/xyz", Where "abc" is the first "layer" and "xyz" is the second "layer". We need to find a way to properly identify a menugroup and a submenugroup, because it could be, that a developer adds a menuitem with a "/" in the name and they don't want to add a submenugroup.

**Comment by rjahn** [comment]
The configuration is just a string. We don't have any escape characters right now. So if there's a / in the string, it's the mark for a group.

The title of the screen is a separate field, so it shouldn't be a problem to set "I/O control" as screen title.

**Comment by maximilianweidenauer** [comment]
Right, I'll adjust this then.
