### ISSUE TITLE
Extendable components

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#189]
It should be possible to extend our standard components like Button, e.g.

User wants to override/extend standard behaviour on click. Add an event listener or replace standard event handling.

**Comment by maximilianweidenauer** [comment]
I've added the event handlers to the available components and I'm exporting them to the example.

In the example I've created an example and wrote a readme doc like for the other features.
https://github.com/sibvisions/reactUI.example/tree/main/src/readme-files/extend-components

Is this done now?
