### ISSUE TITLE
Opening a workscreen redraws the menuitems of current group

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#191]
If we use the "standard" application frame and open a screen via menu, the menu group will be updated. It closes/opens?

**Comment by maximilianweidenauer** [comment]
Wrong if check + when a closeScreen response came, I always notified the menu that selectedMenuItem was empty, then when an openScreen came i pdated the selectedMenuItem -> unnecessary render which was also a problem.
Now I check if there is an openScreen when closing to prevent that from happening.
