### ISSUE TITLE
ComboBox with table in popup?

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#194]
Is it possible to show a table in a combobox popup?

**Comment by maximilianweidenauer** [comment]
Is a combobox popup a popup like in this ticket?
https://github.com/sibvisions/reactUI/issues/193
Then this isn't supported... if it is a "normal" popup "screen_modal" it should work

**Comment by rjahn** [comment]
No, its the popup of a link cell editor… Show a table instead of a list…

**Comment by maximilianweidenauer** [comment]
This doesn't seem to be possible with PrimeReact

**Comment by rjahn** [comment]
hard to implement?
shouldn‘t a big problem?

**Comment by maximilianweidenauer** [comment]
We probably need to use the Material Autocomplete instead of PrimeReact...

https://stackoverflow.com/questions/66005016/material-ui-autocomplete-show-suggestions-in-table-format-with-header-attached-t

in this posts comments is a codesandbox in which Materials Autocomplete "listComponent" property is set as a table.

**Comment by gimmixAT** [comment]
is there an example in jvxmobile? there might be a way to do this with the default primereact dropdown and some templating & css trickery.

**Comment by rjahn** [comment]
not yet. will create an example asap. You could use any dataprovider to test… in the meantime

**Comment by maximilianweidenauer** [comment]
features user components screen should have one, thats where the screenshot I‘ve sent you is from. You can test it in the swing demo

**Comment by gimmixAT** [comment]
thanks, it is indeed on the component screens' group selects

**Comment by maximilianweidenauer** [comment]
CellProfile also needs to be available and table rows odd and even styling (like normal table)

**Comment by rjahn** [comment]
The Components screen now contains a cell format. The format is also sent (with latest SVN update). Maybe the ID is wrong? Server sends the id of the editor...

**Comment by rjahn** [comment]
table styles should be applied as well. If we use basti_mini, the table is not recognizing the mini formats.
