### ISSUE TITLE
Menu button focus rect

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#200]
If you click on the arrow button, the focus is shown with a vertical line.
If you click on the left are, the focus is shown without a vertical line.

**Comment by rjahn** [comment]
Simple Contacts (DB) screen of features user

![image](https://user-images.githubusercontent.com/1307043/141104994-137330ad-162c-4549-a9d5-971c4e15f9ba.png)

**Comment by rjahn** [comment]
hm... but Components are working:

![image](https://user-images.githubusercontent.com/1307043/141106161-cf975aa5-8a9a-478c-9435-789b274bb786.png)

**Comment by rjahn** [comment]
Can't work because styles are missing:

![image](https://user-images.githubusercontent.com/1307043/141106820-5b04681e-b8d5-4c70-b257-2bceec809b5b.png)

**Comment by maximilianweidenauer** [comment]
what do you mean by "styles are missing" are the outcommented styles the styles you added? for me it looks like this in devtools: 
![image](https://user-images.githubusercontent.com/66732863/141312074-be9fd9a8-6f45-4d92-b1a8-bcb4ff180cf4.png)

**Comment by rjahn** [comment]
the styles from my comment… and the green styles from my screenshot…
without it won’t work
