### ISSUE TITLE
React error #185

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#205]
Error: Minified React error # 185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Zs — react-dom.production.min.js:230
ma — react-dom.production.min.js:163:515
ma
u — useComponents.tsx:70
nn — SendOnLoadCallback.ts:60
mn — PanelReportSize.ts:29
reportSize — UIPanel.tsx:65
(anonyme Funktion) — FormLayout.tsx:668
(anonyme Funktion) — FormLayout.tsx:690
(anonyme Funktion) — FormLayout.tsx:702
is — react-dom.production.min.js:211:320
yl — react-dom.production.min.js:257:306
(anonyme Funktion) — scheduler.production.min.js:19:467
$s — react-dom.production.min.js:239:100
$s
(anonyme Funktion) — react-dom.production.min.js:123:115
(anonyme Funktion) — scheduler.production.min.js:19:467
Wi — react-dom.production.min.js:123
Ki — react-dom.production.min.js:122:496
Zs — react-dom.production.min.js:230:156
ma — react-dom.production.min.js:163:515
ma
(anonyme Funktion) — useComponents.tsx:156
forEach
value — ContentStore.tsx:470
value — Server.ts:317
value
u — runtime.js:63
(anonyme Funktion) — runtime.js:293
r — asyncToGenerator.js:3
s — asyncToGenerator.js:25
promiseReactionJob
ts — react-dom.production.min.js:209:201
(anonyme Funktion) — react-dom.production.min.js:226:169
po — 2.8b0b5ed9.chunk.js:2:1186114
os — react-dom.production.min.js:212:494
fl — react-dom.production.min.js:255:232
fl
(anonyme Funktion) — scheduler.production.min.js:19:467
hl — react-dom.production.min.js:248:373
$s — react-dom.production.min.js:239:379
$s
(anonyme Funktion) — react-dom.production.min.js:123:115
(anonyme Funktion) — scheduler.production.min.js:19:467
Wi — react-dom.production.min.js:123
Ki — react-dom.production.min.js:122:496
Zs — react-dom.production.min.js:230:156
ma — react-dom.production.min.js:163:515
ma
(anonyme Funktion) — useComponents.tsx:156
forEach
value — ContentStore.tsx:470
value — Server.ts:317
value
u — runtime.js:63
(anonyme Funktion) — runtime.js:293
r — asyncToGenerator.js:3
s — asyncToGenerator.js:25
promiseReactionJob
Server.ts:163

**Comment by maximilianweidenauer** [comment]
#217 was based on this
