### ISSUE TITLE
table fast scroll problem

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#219]
if you use a touchpad e.g. MacOS and scroll up with a swipe, then the table shows no records -> swipe down -> records available.

Tested with Safari. No problem with Chrome.
No console errors.

**Comment by maximilianweidenauer** [comment]
The new PrimeReact version, which released yesterday, changed the virtualscroller in the table. We could try if that fixes the problem, if not, I will have to test it with a mac... On windows this doesn't seem to happen...

**Comment by rjahn** [comment]
could try it…

**Comment by rjahn** [comment]
Not reproducable with current version
