### ISSUE TITLE
ToolBarPanel gaps

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#232]
Please add 1px or 2px gap between toolbar components.

Test: ToolBar screen of features user

Hover fast with mouse or check the gap between + icon and "Nxt 2"

**Comment by maximilianweidenauer** [comment]
The server sends a FlowLayout without gaps `FlowLayout,1,1,1,1,0,0,0,0,0,3,false`, is it possible to send one with gaps? Or should I add an extra condition

**Comment by rjahn** [comment]
server now sends 1 for vgap and hgap.

**Comment by rjahn** [comment]
be sure that it's possible to change the gap via css...
