### ISSUE TITLE
MenuButton aria support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#233]
To make the menu button accessible for people with impairments  it should implement the aria-haspopup attribute.

https://www.barrierefreies-webdesign.de/knowhow/links-oder-buttons/menu-button.html

**Comment by maximilianweidenauer** [comment]
PrimeReact sets this attribute for right part of the menubutton. Should I also add it to the other part?

**Comment by rjahn** [comment]
Yes, also on the left part - both aria tags.
