### ISSUE TITLE
dark mode error bar

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#239]
error bar in dark mode should be "white" or lightgray?

the standard color is "invisible"

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/145765309-97f245c0-85d4-440e-9fe8-e426e7a84dbf.png)
You mean this error bar? I think this looks ok, does it look different for you or do you not like it?

**Comment by rjahn** [comment]
Yes I don't like it. Tthe background of the bar is too dark.

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/145778133-0e3126a1-40e2-49ef-9966-dcb64b201d24.png)
default is fine for dark-mode or even darker than that?

**Comment by maximilianweidenauer** [comment]
I've adjusted the color... is this ok?
![image](https://user-images.githubusercontent.com/66732863/147089529-f8bfdfdb-c8fb-4073-a6d7-747a36ff75c6.png)
