### ISSUE TITLE
Simple alive check

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#243]
We should implement a simple alive check -> check every 30 seconds (-> configurable)?

Simply send an **ALIVE** through the websocket. The result will be a simple **OK** text.
If application is not alive -> socket connection will be closed with status: 1001 (GOING AWAY)

Also check if socket was closed and is not available. For this case we could do a simple request e.g. /api/changes and if there's a problem or http status-code: 410 (GONE), we know that something happened.

Also the server will send a command: **DISPOSE** if application has expired....

In case of a network connection problem, the alive will fail.... so we should support a (configurable) alive-retry, e.g. 4 times.... and after 4 retries -> error

We could show a permanent message and lock UI in case of retry chain (start after first failure)

**Comment by rjahn** [comment]
interval should be configurable

**Comment by rjahn** [comment]
ALIVE via push makes no sense -> websocket has a session and http request has another session.
There's a new api/alive command, but if we use a websocket, this command shouldn't be relevant for alive handling.

We should test different scenarios:

* short network interrupt (retry should work, no session expire)
* network connection lost (-> only startup possible -> session should expire on server-side)

Close browser or reload -> application should timeout

The server checks if client is running via websocket automatically. If websocket is open -> running -> no websocket connection -> 30 seconds later, still no websocket -> application will be destroyed.

Currently, the timeouts are not configurable, maybe necessary.

**Comment by maximilianweidenauer** [comment]
We need a alive interval timer which can be set in application.xml @rjahn

**Comment by rjahn** [comment]
aliveInterval (milliseconds) is now available in mobile.xml. Default value should be 30000 if aliveInterval is not available in applicationMetaData response.
