### ISSUE TITLE
Login layout looks wrong

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#248]
![image](https://user-images.githubusercontent.com/1307043/147156058-b3090f50-5105-4ae7-b7af-bcb1cf10a788.png)

Checkbox and button -> no gap 
Forgot password -> another place?
checkbox-text not valigned with checkbox

**Comment by maximilianweidenauer** [comment]
Added a gap between forgot password and checkbox-text

Also aligned checkbox-text to checkbox
