### ISSUE TITLE
Change password looks wrong

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#261]
![image](https://user-images.githubusercontent.com/1307043/151806251-759becfd-30fb-4207-8d7c-e0b2e5ee263f.png)

Can't enter old password.

**Comment by rjahn** [comment]
More space between confirm password and buttons

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/151981872-36193290-3414-46d9-a46f-a6718275cf60.png)
I've adjusted the gap between the buttons and the last field, also the old password isn't disabled anymore.
I've also fixed the line height so they're in the middle of the input, and the placeholder color is also lighter in darkmode, it used to be almost not readable
