### ISSUE TITLE
Event problems

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#262]
Sometimes exceptions like:
  `java.lang.IllegalArgumentException: Component with id 'Cus-VF_NT_customer' was not found!`

occur.

If you have a MorphPanel and switch between list and detail (tested with modern web application from VisionX - store).

The problem is not easy to reproduce - only sometimes!

**Comment by maximilianweidenauer** [comment]
fixed in 3199a82306b616771e357029d1e2245d8e1a4e42 thanks to proper requestqueue
