### ISSUE TITLE
Problems with "Enable Search"

### ISSUE THREAD

**Issue by tlehner1203** [sibvisions/reactUI#267]
When enabling the search function in a table following problems happen:

1. The search Button is styled wrong in the table menu 
![image](https://user-images.githubusercontent.com/66067532/156009192-6176cca5-09d9-4bcd-8da2-4a822f9bb536.png)
2. When pressing the Button the current row is colored green instead of a newly added row to search the data in
![image](https://user-images.githubusercontent.com/66067532/156009283-41f6e69f-0c37-4a12-b77f-d174e2b98f2c.png)
which results in further problems down the line as the search doesnt work properly

**Comment by maximilianweidenauer** [comment]
It doesn't seem like I get informations, that i should add a new row, in which I'm able to search.

**Comment by MToerpe** [comment]
3. If you click the button and there is no data in the table, the page is reloaded, but nothing is shown.

**Comment by jmfogl** [comment]
3. When pressing the button and there is no data in the table, then the page is reloaded and after the reload a white page is shown.

**Comment by maximilianweidenauer** [comment]
Thanks... FYI: white page = crash.

**Comment by rjahn** [comment]
The "inline" search is not supported right now. The server doesn't send a changed response. 
This feature requires a server update.

**Comment by rjahn** [comment]
Please test with latest update, should work.

**Comment by rjahn** [comment]
another try
