### ISSUE TITLE
V2: SetValues returns empty response

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#274]
When trying to change a value (I've tried Up- and Download Checkbox and Contacts (DB) FirstName textfield) I send the setValues request to the server, but the response is empty. When I'm changing back to v1 everything works as expected.

It used to work a few days ago I think

sending to: /v2/api/dal/setValues

request: 
![image](https://user-images.githubusercontent.com/66732863/157261778-0b36c66d-16d9-4eb9-b9ef-7dfc79159a4f.png)

response:
![image](https://user-images.githubusercontent.com/66732863/157261832-7dd302d5-d202-4f01-a63b-39b84bc03150.png)

**Comment by rjahn** [comment]
There's no difference between v1 and v2. It's the same code. Requires a debug session.

**Comment by rjahn** [comment]
responses should be available in latest revision
