### ISSUE TITLE
URL parameter forwarding

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#286]
The URL:

`http://jrmb.local:8080/demo/?language=de&Application.Login.username=admin&Application.Login.password=admin`

should send Application.Login.username and password to the application?

**Comment by maximilianweidenauer** [comment]
It does for me...

URL: 
http://localhost:3000/?langCode=de&appName=vxdemo&baseUrl=http%3A%2F%2Flocalhost%3A80%2Fservices%2Fmobile&**username=tickettest123**&**password=tickettest123**#/home

![image](https://user-images.githubusercontent.com/66732863/163993075-9fc13c74-223d-495b-9f47-af277cc37b6b.png)

**Comment by maximilianweidenauer** [comment]
Or should the "username" and "password" property be renamed to "Application.Login.username" and "Application.Login.password"

**Comment by rjahn** [comment]
My property:

  Application.Login.username=admin

is a different property.

**Comment by rjahn** [comment]
If I send additional properties, client should forward to server....

**Comment by maximilianweidenauer** [comment]
Now I get it. For me, this works too. Or am I missing something?

![image](https://user-images.githubusercontent.com/66732863/163993675-b69ca93e-c7df-4ad2-be8d-6f13006459b3.png)
