### ISSUE TITLE
fold menu folds menu entries

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#290]
expand a menu in full-screen mode, fold the menu with < button -> menu will be folded as well.

I thinks it's better if we keep it expanded?

**Comment by maximilianweidenauer** [comment]
I can do that, but I remember that we had some feedback te other way round as well. So I probably adding a flag so it can be easily changed

**Comment by maximilianweidenauer** [comment]
Added a flag in Menu.tsx, maybe we can add some settings for to set this flag in the future?

**Comment by rjahn** [comment]
Please support the flag via server style.... 

Do you request the server during startup?

**Comment by maximilianweidenauer** [comment]
No, I'm currently not requesting the style. I'm opening this ticket again for this issue

**Comment by rjahn** [comment]
Style is for mobile devices.... So ignore requesting style.

New property in applicationMetaData response:

foldMenuOnCollapse (boolean) -> default, if not set -> false
