### ISSUE TITLE
Desktop background not recognized

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#297]
Use configuration of: #295 

Use latest Server from SVN and change following in LaunchCommand.java

`if (projx == null || projx.isDestroyed() || !projx.isConnected())`

->

`if (projx == null || !projx.isDestroyed() || !projx.isConnected())`

With this code, the application won't do an automatic logout after session expires.

If you press Browser Reload -> logout will be done and login will appear, but the desktop image is wrong. Also after login, no desktop image.

Not sure if this a real use-case, but we should check this case!

**Comment by maximilianweidenauer** [comment]
After the browser reload, I only receive the DesktopPanel and the shadow icon at the top. The usual image is missing in the response.
![image](https://user-images.githubusercontent.com/66732863/166654048-13359231-82c0-48ef-9a57-5eef7e699ef5.png)

**Comment by rjahn** [comment]
This was a problem on server-side. The UI was changed during sending of response and not before.
