### ISSUE TITLE
dark mode - tree not nice

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#301]
click on the tree expand icon -> not nice in dark mode

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/167820772-c750142d-1996-461b-aacb-b626a12b1261.png)
Sub 1 arrow is when hovering

**Comment by rjahn** [comment]
An idea: Is it possible to show odd/even background color - if easy (optional)?

**Comment by rjahn** [comment]
And in standard mode (not black)?

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/167844759-9458c807-0bae-4c20-b394-d851bb9039dc.png)
![image](https://user-images.githubusercontent.com/66732863/167844966-0de45ac4-3fad-49b1-8d34-2e1026a3434f.png)
