### ISSUE TITLE
toast not closable with x

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#304]
click on x doesn't close toast

**Comment by rjahn** [comment]
e.g. Save error test screen

**Comment by maximilianweidenauer** [comment]
The 'x' is just an error indication, I can make the toast closable though

**Comment by maximilianweidenauer** [comment]
like info would be an i with a circle

**Comment by rjahn** [comment]
close with click or another icon?

**Comment by maximilianweidenauer** [comment]
With another icon

see: https://www.primefaces.org/primereact-v7/#/toast

**Comment by maximilianweidenauer** [comment]
Closed because toast will not be used anymore once #309 is completed
