### ISSUE TITLE
tabset closes more than one tab

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#305]
Tabset test screen

closed middle tab - first was selected

useLayoutEffect(() => {
  80 |    if (onLoadCallback) {
  81 |        if (props.compSizes && props.compSizes.size > 0 && props.selectedIndex !== -1) {
> 82 |            const selectedPanel = props.compSizes.get(props.components[(props.selectedIndex as number)].props.id)?.preferredSize;
     | ^  83 |            if (selectedPanel) {
  84 |                const prefSize:Dimension = {height: selectedPanel.height + 48, width: selectedPanel.width};
  85 |                sendOnLoadCallback(id, props.className, prefSize, parseMaxSize(props.maximumSize), parseMinSize(props.minimumSize), undefined, onLoadCallback)

**Comment by maximilianweidenauer** [comment]
I've fixed the crash, but now the closing isn't correct, seems to be a PrimeReact bug with onClose and dynamic created Tabs.

In the demo, there are 5 tabs when I close the third tab, the forth doesn't get displayed anymore, so there are only 3 remaining but there should be 4, in my array which I pass to the "TabPanel" component are 4 Tabs.

I've created a ticket in the PrimeReact repository:
https://github.com/primefaces/primereact/issues/2842

**Comment by maximilianweidenauer** [comment]
They keep pushing exactly this ticket back...

**Comment by maximilianweidenauer** [comment]
Changed to 3.0 because this isn't fixed in PrimeReact yet

**Comment by rjahn** [comment]
Current status?
