### ISSUE TITLE
toolbar element gap missing?

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#308]
<img width="185" alt="image" src="https://user-images.githubusercontent.com/1307043/166699102-c96b9207-8dbc-4fd6-bc87-578a0c869470.png">

focus is cut off?

**Comment by maximilianweidenauer** [comment]
The server sends `layout: "FlowLayout,1,1,1,1,1,1,0,0,0,3,false"` so the gap between the elements is only one px, the focus-rect ~3px thats probably why it looks like that. Will the server change that or should I try to increase the gap with messing with the layout

**Comment by rjahn** [comment]
No the layout is fixed... In this case the style should be changed. It would be good enough if focus is "over" the other component or increase the gap - but use styling for this - otherwise it's not possible to create themes
