### ISSUE TITLE
Split drag performance

### ISSUE THREAD

**Issue by Michael-Schober** [sibvisions/reactUI#31]
After one stops to drag the split, most components are locked as, the layout is still calculating

**Comment by maximilianweidenauer** [comment]
53285b876d0b84a9efef16e4e6d5a330083af067  Using throttle made by underscore, increased throttle timer. Before, if you dragged for a long time and then changed screen, the screen would change after ~10 seconds. After the change the screen changes like always. This also fixed a crash.
