### ISSUE TITLE
Error popup styling

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#315]
Popup should be resizable
Red in title -> #CC0C39
x in title -> also white (like the text)
Title is too high

Remote focus of X -> shouldn't be focusable

Table is not styles as other tables -> see direct comparison

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1307043/169802135-c9174200-e6d3-4230-b0bf-8148a31639c5.png">

Details on/off shows in wrong size:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1307043/169802398-b9060f4f-f377-41e6-94be-9215e9fc7ffd.png">

**Comment by rjahn** [comment]
more space between image and text in description...

**Comment by maximilianweidenauer** [comment]
It is styled differently because it is not a Table, it is a Listbox but I'll do my best to make it look similar.

**Comment by rjahn** [comment]
OK.

**Comment by maximilianweidenauer** [comment]
What do you mean with title is too high? Its in the middle of the header

**Comment by rjahn** [comment]
I mean the whole title-bar. Please reduce padding.

**Comment by maximilianweidenauer** [comment]
Ah ok

**Comment by maximilianweidenauer** [comment]
Reworked Error-Dialog style:

- no details:
![image](https://user-images.githubusercontent.com/66732863/170020053-a9207880-8827-4df1-b5b8-4b2b4d1c7592.png)

- details: 
![image](https://user-images.githubusercontent.com/66732863/170020123-566b35cb-cb63-4725-91bc-26ba904b70a8.png)

- resizable:
![image](https://user-images.githubusercontent.com/66732863/170020191-264fe946-acde-4063-8439-213232c26d78.png)
![image](https://user-images.githubusercontent.com/66732863/170020312-e9791583-8d0a-4ed6-9ff4-6c3813f3fea3.png)

When clicking details off, it returns to its standard size

**Comment by maximilianweidenauer** [comment]
I forgot the gap between the image and text... adding it now

**Comment by rjahn** [comment]
the message area shouldn't resize!

**Comment by rjahn** [comment]
if details are visible -> resize details area

**Comment by maximilianweidenauer** [comment]
so basically the top part (message) should always look the same and the bottom part (details) should be resized?

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/170230092-4611a29a-a0cf-4281-a2ac-916b9fb62d83.png)
Message area is not resizing anymore

**Comment by rjahn** [comment]
Resizing is great!
Icon position is not good -> Text with only one line is not v-center aligned...

**Comment by maximilianweidenauer** [comment]
This was an old screenshot, you gave me more feedback on Slack and I've shown you more pictures there...

But here is the current state.

![image](https://user-images.githubusercontent.com/66732863/173347961-9e7071af-f207-4e76-90ee-329b3520b8f0.png)

**Comment by maximilianweidenauer** [comment]
It's not looking too great with multipole errors, I have to tweak more

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/177481330-fd5994a5-0c94-4507-9f7e-ae2d449639d7.png)

![image](https://user-images.githubusercontent.com/66732863/177481385-9ec751cd-6094-48c2-b8e0-3d29467008cb.png)

**Comment by maximilianweidenauer** [comment]
Resizing works pretty good in my opinion

**Comment by rjahn** [comment]
Looks great!

I wrote the question because you said: 

> It's not looking too great with multiple errors, I have to tweak more

**Comment by maximilianweidenauer** [comment]
Yeah I probably forgot updating because something else was coming up, but now I'm going to close this
