### ISSUE TITLE
LinkedCell editor in table 

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#316]
Is it possible to show the full button?

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1307043/169803072-bfddaba7-4f04-4894-b481-9d412fb02bac.png">

And is it possible to make it a little bit bigger to hide selection behind the editor?
There's some space between cell border and editor (left and right).

**Comment by maximilianweidenauer** [comment]
I've reduced the space between cell border and editor and fixed the button.
![image](https://user-images.githubusercontent.com/66732863/170019070-b237c1e7-85db-460b-b232-eb505b79227f.png)

**Comment by maximilianweidenauer** [comment]
Also I've removed the box-shadow (focus) because I thought it wasn't good looking

**Comment by rjahn** [comment]
great
