### ISSUE TITLE
App version sent from server-side

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#322]
It should be possible to configure the app version 1 or 2 via config.xml/server-side application:

If server doesn't send the version -> use app_version.json

We should also rename the app version because it's not a version.

Server will send: transferType: "partial" or "full" in applicationMetaData.

Please rename the appVersion to transferType and use "partial", "full" as values.

"partial" is default if server doesn't contain transferType in response.

**Comment by rjahn** [comment]
current server repo already contains the transferType

**Comment by maximilianweidenauer** [comment]
Closing this because we dont support this anymore
