### ISSUE TITLE
ComboBoxEditor cancel edit throws an error

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#325]
Opened the Popup for Groups in Components screen. Insert a new record, press pencil - press Escape

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/1307043/177191616-c07534bd-8e89-4301-a671-8254153dd914.png">

**Comment by maximilianweidenauer** [comment]
Something else must have been going on there... Seems like a timeout or a session-expired happened during your test. Because the errorbar activated.

Nevertheless its still a bug, I will try to reproduce it.

**Comment by maximilianweidenauer** [comment]
Or the server returned an error?

**Comment by rjahn** [comment]
Deleted: npm_modules, package-json.lock and run npm install
Cleared browser cache

Problem is not reproducable
