### ISSUE TITLE
PrimeReact 10.0.0

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#334]
PrimeReact seems to have fixed the refs so now we could upgrade

**Comment by maximilianweidenauer** [comment]
I'm testing the new PR version 8.6.0 in https://github.com/sibvisions/onlineHelp, they have reworked the refs. Eg. instead of calling ref.current.element, now there is a function to call ref.current.getElement(). I should update on a different branch when I find the time to do so.

**Comment by rjahn** [comment]
Current status -> different version!
