### ISSUE TITLE
Use layoutMode in web environment

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#337]
The layoutMode (Mini, Small, Full) is available as response of /deviceStatus request.

Mini: No sidebar
Small: Small sidebar width (only icon and some characters - fade out text)
Full: Full sidebar width (icon and all characters)

Currently, we don't use the layoutMode... Is it possible to replace the media query with layoutMode?

**Comment by maximilianweidenauer** [comment]
Is this still relevant? This is already used with devicestatus.

**Replacing media query with layoutMode/devicestatus:** 

I don't think we can entirely replace the media query, I think we need to use a mix of both, javascript (devicestatus) and CSS (media query). As it already is.

**Comment by maximilianweidenauer** [comment]
Actually, now that I think about it... I could just change the classNames of the elements which need to be adjusted...

I would still need to use some media query though, because PrimeReact also has some media query rules, which I must overwrite.

**Comment by rjahn** [comment]
try what's possible.
