### ISSUE TITLE
Different Loading-Animation Support

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#345]
In the future it should be possible to change the loading-animation to a custom one

**Comment by maximilianweidenauer** [comment]
I'm now supporting:

- PNG's
- JPG's
- SVG's

The image has to be in the directory "public/assets" and the name of the file has to be "loading_screen_image". Let me know if I should change the name of the file. Should I also update the Readme to show that this is possible?

**Comment by maximilianweidenauer** [comment]
I could do that, maybe loading some extra properties from the app.json file like:

- loading-background
- loading-text
- loading-image-position
- loading-spinner-position

**Comment by rjahn** [comment]
The problem is that we don't know the styling preferences of our users.... but a different image and background is not wrong.

Is it possible to define a own loading "page" via react UI api?
