### ISSUE TITLE
SetValuesCommand/SetValuesRequest has additional property "columnName"

### ISSUE THREAD

**Issue by mhandsteiner** [sibvisions/reactUI#348]
The SetValuesCommand has an additional property columnName in future. If not sent, server behaviour does not change.
If columnName is sent, the server will additionally check, if the specific column is read only, and will open an Error View.
The columnName is the column, that is edited (caused the SetValuesCommand).

**Comment by rjahn** [comment]
The property columnName is now editorColumnName
