### ISSUE TITLE
Menu items without group

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#356]
In corporate menu it should be possible to add menu items without menu -> means clickable menu items in the menubar.

Two options: server sends flat: true|false for a menu or a menu item?

flat menu -> all items flat
flat item -> only item flat

**Comment by maximilianweidenauer** [comment]
Is the flat property implemented, I've checked `MenuAnalyzer.java` and can't find it. If it is implemented is there a test or how can I set it to test it out.

**Comment by rjahn** [comment]
Not implemented right now.

**Comment by rjahn** [comment]
Please use user: layout and latest mobile server from repo.

All menu items should be flat....

**Comment by rjahn** [comment]
We don't have group entries... If all entries of a group are flat -> hide group because it will be empty
