### ISSUE TITLE
toolbar and menubar visibility not recognized correctly

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#359]
The application settings response contains information about toolbar and menu visibility.

In standard application frame, the menu is only visible if toolbar AND menu are visible
In corporation application frame, the menu and toolbar(=sidebar) are independent.

**Comment by maximilianweidenauer** [comment]
In standard application frame the menu is now only visible when toolbar and menu are set to visible, previously it was only when menu was true.
