### ISSUE TITLE
Signature with lock mode

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#362]
We have a new property for Signature Pad... this is useful for flutter UI because scrolling is done with touch events.

I'm not sure if this property is relevant for reactUI.

But it's maybe a good idea to have the same UX as in flutter UI.

**Comment by maximilianweidenauer** [comment]
I've put the reactUI in "phone/mobile mode" (F12 and mobile icon at the top left) and checked if the scrollpanel would scroll when I was drawing, but the ScrollPanel didn't scroll, so I guess this property isn't relevant for me. If I understood the property right.

**Comment by rjahn** [comment]
You scroll with mouse wheel?

By touch events its the case that scroll event is consumed if you try to scroll a signature pad. It's painting instead of scrolling. In your case it should continue scrolling...

**Comment by maximilianweidenauer** [comment]
When scrolling with mouse wheel, scrolling works. 

When touching the scroll event is consumed

**Comment by rjahn** [comment]
Did you test with a real phone? Is usage clear?

**Comment by maximilianweidenauer** [comment]
Just tested with my iPhone 13, imo works as expected, when touching/scrolling outside of the signature pad, scrolling is possible, when you are touching/drawing inside of the signature pad, scrolling isn't possible

**Comment by rjahn** [comment]
and this is the reason for this ticket. If you touch the signature pad but think the page should scroll.... it's not what you expect.

If you lock the signature pad, you can't draw... so you scroll until you unlock - to - edit.

**Comment by rjahn** [comment]
please check flutter implementation as reference

**Comment by maximilianweidenauer** [comment]
should now work as in flutter
