### ISSUE TITLE
Auto-Restart on session-expired

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#370]
Introduce a new parameter:

"autoRestartOnSessionExpired": true

If enabled, don't show session expired and automatically restart.

**Comment by maximilianweidenauer** [comment]
for app.json?

**Comment by maximilianweidenauer** [comment]
Checking for "autoRestartOnSessionExpired" in app.json and if auto-restarting I'm logging a message: "Session Expired! Restarting."
