### ISSUE TITLE
User menu too small

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#373]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/1307043/219308209-49f08c3f-888e-4e47-9ca2-79929f52fbc4.png">

**Comment by rjahn** [comment]
and also rename Info to About...

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/219311401-34c3d79c-bc98-4623-965c-275ca1ecd36d.png)
increased size to min-width 180px --> when a displayname was short, the profile menu got short as well, now I've introduced a min-width.

Is this ok now or does it look weird? Do you just want the dropdown to be bigger?

**Comment by rjahn** [comment]
Only the dropdown...

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/219346302-3b9e1271-71e9-40c8-bf5a-9ca7a0b7d93c.png)
I think this will be good enough?

**Comment by rjahn** [comment]
test German translation as well and if it doesn't wrap, google enough!
