### ISSUE TITLE
alive doesn't stop

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#374]
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/1307043/219867116-b861a513-eddc-41fd-9ed0-cc23566256f3.png">

**Comment by rjahn** [comment]
and not sending request while error is active?

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/1307043/219901949-dafb75e1-9e1d-4bdd-826f-1ecc0344704b.png">

**Comment by maximilianweidenauer** [comment]
I'm still sending alive request when an error is active, I'm not sending alive requests when an error is displayed and session is expired.

When do I have to send alive and when not??

**Comment by maximilianweidenauer** [comment]
Pretty sure I've had an issue before with "stop sending alive requests when..."

**Comment by rjahn** [comment]
Needs investigation. 

Expired -> no more alive/websockets -> same as stop application is destroyed
Connection problem -> retries...

But if an Error occured? What does this mean and why is there no retry? Must be something special.

alive also makes no sense if connection is broken? You don't use alive for connection retry?

So only if connection is established, alive makes sense. The alive is more or less a "ping" from the client.
It means, the browser is open and the application is running.

**Comment by maximilianweidenauer** [comment]
While researching, I've just seen that when the Websocket is closing, I'm stopping the alive Interval, I've just added this recently while working on #371. I've added this in commit: https://github.com/sibvisions/reactUI/commit/05ff684267b75daf884f5e63493d53a61dc82057

So short: Websocket close (VisionX close) -> no more alive requests. Is this good enough for this ticket?

**Comment by rjahn** [comment]
If you close websocket, it should work...
but the application also works without websocket. The WS is just for server-driven updates.

So binding the alive handling to the WS is not a good solution.

**Comment by maximilianweidenauer** [comment]
also removed "sending request while error is active" check for alive because the interval isn't active anyways
