### ISSUE TITLE
LabelControl component bold font not working

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#375]
If we use a LabelControl (a bound label), the font is not set in reactUI:

```java
LabelControl labelControl1 = new LabelControl();
labelControl1.setColumnName("SUM_GEFAHRENE_KM");
labelControl1.setDataRow(rdbProtokollSum);
labelControl1.setFont(new UIFont("Default", UIFont.BOLD, 12));
labelControl1.setHorizontalAlignment(LabelControl.ALIGN_RIGHT);
labelControl1.setVerticalAlignment(LabelControl.ALIGN_CENTER);
```

**Comment by maximilianweidenauer** [comment]
I didn't know a bound label existed so dataRow subscription isn't even implemented in the label yet (which I'm going to do now), nevertheless I took your implementation and altered it a bit so I could add it to the ContactsWorkscreen of the demo.
`LabelControl labelControl1 = new LabelControl();
labelControl1.setColumnName("FIRSTNAME");
labelControl1.setDataRow(rdbContacts);
labelControl1.setFont(new UIFont("Default", UIFont.BOLD, 12));
labelControl1.setHorizontalAlignment(LabelControl.ALIGN_RIGHT);
labelControl1.setVerticalAlignment(LabelControl.ALIGN_CENTER);`

In the changedComponents for the label I'm not receiving the dataRow.
![image](https://user-images.githubusercontent.com/66732863/220042918-45229c33-2da3-4141-85bb-e95a16c17c4a.png)

**Comment by rjahn** [comment]
A labelControl is a bound component but the UI shows a Label without binding information - just like a Label. Binding is handled server-side.

**Comment by maximilianweidenauer** [comment]
For me the LabelControl is bold in the demo, maybe if you could send me your application again I can figure out the issue?

Another issue I've encountered is, that when there is **no** row selected at the beginning and I'm then selecting a row, the setText of the LabelControl is inconsistent, I'm sometimes not receiving a text. Then I'm swapping rows until I get one and then it works everytime. Just at the start it is inconsistent.

When I'm selecting a row at the very start in the code, the text works everytime.

**Comment by maximilianweidenauer** [comment]
Don't know if I can do more about that, the font doesn't look that bold but it does have the bold style, maybe looks also a bit misleading because the bold labels are only `font-size: 12px` the labels next to it are 14px and not bold, Could be that the boldness isn't that visible because of that.

**Comment by rjahn** [comment]
You're right. Can't change the font. Use different font or increase size.

**Comment by maximilianweidenauer** [comment]
👍 then I'm closing this issue
