### ISSUE TITLE
websocket connection missing

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#376]
Latest reactUI doesn't start websocket to /pushlistener

**Comment by maximilianweidenauer** [comment]
/pushlistener ist missing for you?

`ws.current = new WebSocket((baseURL.substring(0, baseURL.indexOf("//")).includes("https") ? "wss://" : "ws://") + urlSubstr + "/pushlistener?clientId=" + getClientId()`

Is in the code, but I'll check tomorrow

**Comment by rjahn** [comment]
I see the log

connecting WebSocket

but there's not request in the network tab of Chrome and also no log on server-side?

Also no other websocket message.

**Comment by rjahn** [comment]
The problem is the clientId. If the id contains a #, it won't work.
You should encode the URL parameter...

Anyway, server now sends another id without # in it.

**Comment by maximilianweidenauer** [comment]
now encoding url parameter in websocket url, is this closable?

**Comment by maximilianweidenauer** [comment]
As we talked about, I've added '#' in `HttpSessionHandler.java` and with encoding it works, without it didn't.
