### ISSUE TITLE
Esc or click here for retry not working

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#379]
Makes no difference if I press Esc or the link... 
Request resend is not working?

In my case, login timed out

https://user-images.githubusercontent.com/1307043/219966463-3659bca9-7102-47e2-a115-53187bf131c8.mp4

**Comment by maximilianweidenauer** [comment]
I've put the `requestTimeout` in my `app.json` file to 10 (except for startup), for me, esc and the link do work...

Did you add a sleep in the mobile server or something similar so I can try this? Maybe it behaves differently if the `requestTimeout` is larger.

Also: Can you maybe use the `Filter/XHR` filter in the network tab, so only the relevant requests are shown. In the video I can't even see if a login request was even sent to the server. It looks like it's cropped at the bottom, The last thing you can see is the "logo_login" image fetch in the network tab you can't see the login request.

**Comment by maximilianweidenauer** [comment]
I've added `Thread.sleep(20000);` in the `LoginCommand` the request is being retried when clicking on the link, the Errorbar is just disappearing when retrying, the login button is just not being disabled.

**Comment by maximilianweidenauer** [comment]
Seems to be ok, I've just added the topbar appearing because that was missing, I'll also disable, the button when retrying, currently the buton only got disabled onSubmit, but this is not the case when retrying through errorbar

**Comment by maximilianweidenauer** [comment]
This should also be ok now
