### ISSUE TITLE
Menuitem alignment/icon not nice

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#383]
<img width="237" alt="Bildschirmfoto 2023-03-04 um 23 28 24" src="https://user-images.githubusercontent.com/1307043/222931401-31899c0f-2a02-4db9-8d56-36868556018c.png">

We had the same problem in flutter.

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/223105543-1132546f-bb2f-445e-a365-2d5c62187c03.png)
