### ISSUE TITLE
New openscreen/reopenScreen commands

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#385]
Please switch temporary to v3/openScreen, v3/reopenScreen.

The new openScreen command doesn't force closing screen. 

Use user: save/save
The user has 3 screens: Changes, Changes 2, NO Changes

Open Changes -> press Browser Back, press Forward -> Back shouldn't close the screen instead a message should appear and Forward doesn't show the screen again.

Please test navigation with v3 commands -> we have some problems.

**Comment by maximilianweidenauer** [comment]
fixed in 94e4338926f647f95ab4526da3cd84e5cab37574
