### ISSUE TITLE
concat mask support for linked cell editor referenced databook

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#387]
It would be nice to show data of linked cell editors with concat mask, like [here](https://doc.sibvisions.com/jvx/client/gui/concatmask_linked_celleditor).

Only in case of concat mask set and optional (can be disabled)

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/225567132-0d81febb-fcf1-4b83-88ee-6904d6d81ac3.png)
Would look like this. Tested with Toni's new `ConcatMaskWorkscreen` in the mobile demo.
I've added a flag in the code to either display it with the concat mask or table. I thought about adding a flag in `app.json` what do you think?

**Comment by maximilianweidenauer** [comment]
And should I disable the flag for now?

**Comment by rjahn** [comment]
default: enabled
