### ISSUE TITLE
wrong element size

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#388]
If you use following Java code:

````java
UIFlowLayout flTag = new UIFlowLayout();
flTag.setVerticalAlignment(ALIGN_CENTER);
flTag.setHorizontalGap(3);
flTag.setMargins(1, 4, 1, 1);

UILabel label = new UILabel(pTagLabel);
label.setHorizontalAlignment(ALIGN_LEFT);
  
UIPanel panTag = new UIPanel(flTag);
panTag.addStyleNames("tagpanel", "f_standard_border", "l_trocken");
panTag.setBackground(UIColor.white);
  
UIButton butDelete = new UIButton();
butDelete.setEnabled(editable);
butDelete.setActionCommand("Trocken");
butDelete.setBackground(null);
butDelete.setBorderOnMouseEntered(true);
butDelete.setFocusable(false);
butDelete.setMargins(3, 3, 3, 3);
butDelete.setImage(UIFontAwesome.getImage(IFontAwesome.CLOSE_SMALL, 13));
butDelete.addStyleNames("tagdelete", "f_no_min_size");
butDelete.setVerticalAlignment(IAlignmentConstants.ALIGN_CENTER);
  
panTag.add(label);
panTag.add(butDelete);
````
the element layout is not right.

![image](https://user-images.githubusercontent.com/1307043/227054197-3d0dbcf9-0409-4687-9747-665bade55b5e.png)

Maybe because of f_standard_border?

Also, the layout margin is not right?

<img width="98" alt="image" src="https://user-images.githubusercontent.com/1307043/227054938-ff1b6a24-a405-4893-836e-c6fa4b545202.png">

<img width="93" alt="image" src="https://user-images.githubusercontent.com/1307043/227055262-267389ef-8732-423d-a386-3b21d219c5f5.png">
<img width="93" alt="image" src="https://user-images.githubusercontent.com/1307043/227055366-c1fbe582-7b83-4f4d-a946-7fc532ae0ec3.png">

**Comment by maximilianweidenauer** [comment]
border was an issue in flowlayout, also removed unnecessary margin addition similar to recent formlayout change
