### ISSUE TITLE
Restart support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#39]
The server returns a Restart response, with the name: restart

The response also contains a property: info
It usually contains an exception (the message)

This response can be available if an application was available during startup/login, but was deleted while using...

If a restart occurs, the application should automatically restart. Usually, an error will be shown if an application name is invalid!

**Comment by maximilianweidenauer** [comment]
Implemented in ece4b51eabd3b8988e2cf1c7178616bd5ba3e965
