### ISSUE TITLE
Automatic logout - reset

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#391]
Please check if we support automatic-logout (e.g. after an application connection timeout).
In this case, the server pushes a refresh and the response of the refresh request will return the Login View.

It should be guaranteed that the client clears all caches, like in case of a manual logout.

**Comment by maximilianweidenauer** [comment]
Just tested with `<Application.connection.timeout>1</Application.connection.timeout>`, I'm getting logged out, and I'm calling the reset function of my contentstore.
