### ISSUE TITLE
IMAGE column with null value

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#396]
Use a text column with name "IMAGE" and an image viewer as cell editor. If the value is null, the client tries to get the resource. This request returns 404 and reactUI shows a broken image.

You shouldn't request null.

**Comment by mhandsteiner** [comment]
Example, with null bug and a second one with mapped image to font awesome.
[NullImageViewer.zip](https://github.com/sibvisions/reactUI/files/11650257/NullImageViewer.zip)
