### ISSUE TITLE
Hyperlink component

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#397]
Currently our Hyperlink component is a button. 

With latest version, Hyperlink implementation will send url and target properties as well. We can create a real hyperlink component instead a fake link!

So, if you receive an url and optional target property, use a real hyperlink instead of a button!

In Safari, the popup will be blocked if you use a button. In Chrome and Firefox, this is working!

**Comment by maximilianweidenauer** [comment]
Is there a test available? I've checked in the demo's components screen but there is no url or target.

**Comment by rjahn** [comment]
The components work screen uses Hyperlink, but it doesn't change the url and doesn't use target.

**Comment by rjahn** [comment]
New screen: Hyperlink is available

**Comment by maximilianweidenauer** [comment]
looks the same as before and now is a "<a>" element
![image](https://github.com/sibvisions/reactUI/assets/66732863/3c85a6f6-79ac-4246-8d00-a6d92485fb39)

**Comment by maximilianweidenauer** [comment]
please test with safari

**Comment by rjahn** [comment]
link looks right, but you still send the action event?

**Comment by rjahn** [comment]
This is not a bad thing but the server component shouldn't send you a link back.

**Comment by maximilianweidenauer** [comment]
Yes, I thought I should try to use every event the button also sent, like focusGained and focusLost aswell for example

**Comment by rjahn** [comment]
Works in my environment.
