### ISSUE TITLE
Consider quoted showDocument

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#398]
The ShowDocumentResponse contains an url property.

This property looks like:

  https://www.domain.com/app?param=abc;param2=xyz.doc;bounds;target

but this is also possible:

  "https://www.domain.com/app?param=abc;param2=x;y;z.doc";bounds;target

The last case is currently not supported. Please support quoted URL parameter.

**Comment by maximilianweidenauer** [comment]
checking if URL starts with '"' if yes substring from 1 to last index of '"' for the url which is being linked to and then split up the remaining string by ";" for target
