### ISSUE TITLE
FlowLayout calculates wrong

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#401]
If you have a FlowLayout in center of borderlayout and set margins to the flow layout but not to the borderlayout, components in flowlayout don't use the right margins....

**Comment by maximilianweidenauer** [comment]
In Ticket FS#8424 I've fixed a FlowLayout margin issue, when the horizontal/vertical alignment is "stretch".

Is your FlowLayout stretched aswell, or do you maybe have a screenshot of the screen?

**Comment by maximilianweidenauer** [comment]
I've tried doing it as you described and added some buttons, but I don't really know if there is an issue here...
![image](https://github.com/sibvisions/reactUI/assets/66732863/46738267-30a8-42d2-ae87-041146b047f7)

**Comment by rjahn** [comment]
already fixed
