### ISSUE TITLE
Set Startup Error non closable

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#402]
Currently when the server sends an error-dialog during the startup, it is possible to just close the error, which will lead to an endless loading screen.

Instead make the dialog non closable

**Comment by rjahn** [comment]
or embed the error instead of the loading animation?

Both is a good solution and an improvement.

**Comment by maximilianweidenauer** [comment]
Also improved style of error-dialog, when there is no color-scheme/theme loaded
