### ISSUE TITLE
Full Mode Image Loading

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#403]
In full mode there are some issues with images not being loaded. Mostly all pictures are always requested from the server, shouldn't they be cached?

**Comment by rjahn** [comment]
If you know the URL, just post here. I also had some image loading problems but it depends on the application.

**Comment by maximilianweidenauer** [comment]
I think this is working now?

**Comment by rjahn** [comment]
Will check it.

**Comment by rjahn** [comment]
Looks great
