### ISSUE TITLE
top progressbar position

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#405]
Position of loading progress should be configurable (currently, always top).

It would be nice to show the progress at the bottom.

(Style Designer)

**Comment by maximilianweidenauer** [comment]
So by Style Designer you mean that this should be configurable in the [ReactUI Designer](https://github.com/sibvisions/reactUIDesigner)? I've just implemented configuring the position via app.json, because I didn't see the "(Style Designer)" until now.

It's not an issue just wanting to make sure.

**Comment by rjahn** [comment]
Options: css file
Yes, ReactUI Designer would be nice

If you don't have access to the style infos before startup, just don't show a progress?
It's important after startup - for user feedback, but for the startup process, the loading animation is enough.

I guess that the json file is not the first place where a developer would search.

**Comment by maximilianweidenauer** [comment]
Ok, I'm going to add a css variable, which right now can be edited by application.css, I'll open a ticket in ReactUI Designer to add a field for this variable and implement it, when I'm doing more tickets for the designer.
