### ISSUE TITLE
How to start react-ui locally

### ISSUE THREAD

**Issue by a952454** [sibvisions/reactUI#407]
1. I cloned the latest code and ran npm i.
2. I added the config.json, like this:
  ```
 {
    "appName": "test",
    "baseUrl": "http://cnm1v9ptq3/services/mobile",
    "theme": "basti_small"
 }
```
baseUrl is the live preview address of my local visionx startup.

Then my react project kept loading.

Why is this, is there something I did wrong? Or is there a mistake in filling in the baseurl here?

So can you help me? Thanks.

![image](https://github.com/sibvisions/reactUI/assets/34675560/3bececc9-2c9b-4f23-9d2a-6ba1116fde97)

**Comment by a952454** [comment]
![image](https://github.com/sibvisions/reactUI/assets/34675560/f7ba8166-372f-4062-9ed7-74fbaba1ffa2)

**Comment by maximilianweidenauer** [comment]
Seems like you are stuck during the loading animation

could you please add `"debug": true ` to your config.json. This should show you on which readyParameter the loadingscreen is stuck. Could you then send another screenshot

**Comment by a952454** [comment]
![image](https://github.com/sibvisions/reactUI/assets/34675560/ad18c432-e1f1-4cbd-a064-47ce85fa751c)
@maximilianweidenauer  thank you very much.

**Comment by a952454** [comment]
hi @maximilianweidenauer, did you get the results?

**Comment by maximilianweidenauer** [comment]
Seems like the color-scheme couldn't be loaded, do you have a color-scheme directory in your public directory with a "default.css"   file? Also the translation file is potentially wrong or not available

**Comment by a952454** [comment]
yes, I downloaded the code from github and didn't change anything
![image](https://github.com/sibvisions/reactUI/assets/34675560/faf5a35d-54d5-4307-b8af-937c7f57cd98)

**Comment by a952454** [comment]
Hi @maximilianweidenauer ，  I think I found out what the problem is, I configured the fetch request mode: 'no-cors', although I can get the data, but Response.body is Null, so for this point do you have any way? Can I open cross-domain access to my local visionx?
![image](https://github.com/sibvisions/reactUI/assets/34675560/c3801feb-c605-4e37-96c4-3e830575c004)

**Comment by rjahn** [comment]
Sorry, but this project doesn't cover support for a product like VisionX. You should contact your product support.

reactUI is an open source project and independent.
