### ISSUE TITLE
Introduce API for application parameters

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#409]
It should be possible to set application parameters.

The following command is available (for partial and full):

api/setParameter

Request:

clientId (String)
parameters (Map<String, Object>) -> same as for screen parameters

The API should be available for reactUI developers. We don't set parameters automatically - only programmatically.

-> Also add the API to our documentation

**Comment by maximilianweidenauer** [comment]
tested in example and added api documentation --> screen-parameter doc is now send-parameter doc and contains screen-parameter and set parameter doc
