### ISSUE TITLE
Sort on header click

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#41]
It should be possible to sort tables by click on header: Up/Down/Off (Asc, Desc, Default)

The server-side doesn't support this feature right now!

**Comment by maximilianweidenauer** [comment]
Is it possible that a sort mode is pre-set by the server when the screen is opened?

**Comment by maximilianweidenauer** [comment]
So sorting for single columns is now supported, right now I'm waiting for the server to send me the sortDefinitions, so I can set the currently sorted, de-sorted or multiple sorted columns more efficiently. I'll also have to figure out, how I'll do the CTRL+click sort like in swing, to sort by multiple columns.
