### ISSUE TITLE
internal frame measuring

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#410]
The size of internal frames is not correct. It looks like a default size?

Please calculate the preferred size, if not set.
This is a little bit tricky but it already exists for vaadin UI. So it shouldn't be a big problem to to the same in reactUI.

**Comment by maximilianweidenauer** [comment]
So internal frames should always be their preferredSize, I thought a default size was fine and only use the calculated size if the property "pack" is set to true

**Comment by rjahn** [comment]
If we call pack, the size should be calculated -> correct

If user sets a size/pref size... we should use it.

Best: talk to mh next week. We should do it like in vaadin UI.

**Comment by maximilianweidenauer** [comment]
After talking with hm he told me how I should handle the preferredSize of an InternalFrame
