### ISSUE TITLE
custom readAheadLimit for openScreen

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#417]
Currently, the readAheadLimit can't be set for specific screens. The default value (startup request) will be used automatically.
It would be nice to set the readAheadLimit for openScreen request.

The property name is

  readAheadLimit

for open screen request.

**Comment by maximilianweidenauer** [comment]
property readAheadLimit, can now be passed to self created openScreen-requests and api command "sendOpenScreenRequest"
