### ISSUE TITLE
Toolbar Button Height not correct

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#421]
Toolbar Button Height not right for button(s) without text.

<img width="168" alt="Bildschirmfoto 2023-09-29 um 09 17 10" src="https://github.com/sibvisions/reactUI/assets/1307043/15f01ec6-9f2c-427b-b00a-b06f408ad217">

<img width="176" alt="Bildschirmfoto 2023-09-29 um 09 17 23" src="https://github.com/sibvisions/reactUI/assets/1307043/10aac2c5-bdbb-45d1-af1b-0d82448f51f7">

**Comment by maximilianweidenauer** [comment]
The FlowLayout is not stretched and the size of the Button without text is smaller than the others. 

If the FlowLayout is vertically stretched, then the Button would be at the correct position

**Comment by maximilianweidenauer** [comment]
In bde4b462b302cf94afe8a1233be867e7a67a9b9f I fixed an issue where the margins of a toolbar weren't correct (see your second picture "Aktualisieren" Button is all the way to the right)

While testing I've seen that the "X" Button is now stretched, did you fix that? If yes this ticket can be closed! 👍

**Comment by mhandsteiner** [comment]
Problem is fixed server side. The layout is now properly stretched (vertical stretch in case of horizontal toolbar and horizontal stretch in case of vertical toolbar).
