### ISSUE TITLE
Support readonly format

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#424]
FetchResponse has a new property: 

```
"recordReadOnly" : {
  "records" : [ [ 1, 1, 0 ], [ 0 ], [ 1, 1, 0 ], [ 1 ], [ 1, 1, 0 ] ]
}
```

1 = editable
0 = readonly

The elements are in the same order as the columnNames.
If the number of elements is smaller than the number of columns -> repeat last number:

```
[0, 2, 0, 1, 1, 1] => [0, 2, 0, 1]
[0, 0, 0, 0] => [0]
[1, 1, 1, 1] => [1]
```

A test screen is available: **ReadOnly Checker** -> features user.

**Comment by maximilianweidenauer** [comment]
Test screen works with implementation
