### ISSUE TITLE
ICheckBoxCellEditor should support special looks depending on defined style names

### ISSUE THREAD

**Issue by mhandsteiner** [sibvisions/reactUI#432]
The ICheckBoxCellEditor got special style names, to be able to display additionally a radio button, a switch, a toggle button or a normal button.
    /** Display type constant for checkbox. */
    public static final String STYLE_CHECKBOX      = "ui-checkbox";
    /** Display type constant for radio button. */
    public static final String STYLE_RADIOBUTTON   = "ui-radiobutton";
    /** Display type constant for switch. */
    public static final String STYLE_SWITCH        = "ui-switch";
    /** Display type constant for togglebutton. */
    public static final String STYLE_TOGGLEBUTTON  = "ui-togglebutton";
    /** Display type constant for button. */
    public static final String STYLE_BUTTON        = "ui-button";

![image](https://github.com/sibvisions/reactUI/assets/43437457/7d315c12-f2e3-48bd-aebf-8691797d434a)

**Comment by maximilianweidenauer** [comment]
No text set --> use columnLabel

**Comment by rjahn** [comment]
Please post a screenshot of current state

**Comment by maximilianweidenauer** [comment]
![image](https://github.com/sibvisions/reactUI/assets/66732863/703514a0-7687-4995-b7a0-bcc4def06942)

**Comment by mhandsteiner** [comment]
ICheckBoxCellEditor should support additional special look hyperlink

    /** Display type constant for hyperlink. */
    public static final String STYLE_HYPERLINK     = "ui-hyperlink";

The behavior should be the same as the STYLE_BUTTON.

STYLE_BUTTON and STYLE_HYPERLINK should additionall have the possibility to show directly the text, stored in the column itself.
This should be done, in case selected value and deselected value is null.

**Comment by maximilianweidenauer** [comment]
last thing missing was alignment
