### ISSUE TITLE
Customizable character for mandatory mark

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#436]
Currently our table shows a * (asterisk) character for mandatory columns. This is hard coded!

We should introduce new application metadata setting (like userRestart):

mandatoryMarkVisible (boolean)
mandatoryMark (String)

If mark is true -> use char if set (empty or space means set as well), otherwise use *

**Comment by rjahn** [comment]
Rules: 

mandatoryMarkVisible property not found -> true
mandatoryMark property not found -> *


Test: mobile.xml of demo project (JVx.mobile) already contains tags - but as comments

**Comment by rjahn** [comment]
Pushed a solution - please review

**Comment by maximilianweidenauer** [comment]
Your solution works!
