### ISSUE TITLE
Column label padding vs. content padding

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#438]
Table column label doesn't look nice and correct.

<img width="1140" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/c3434203-6f3c-456d-8ac6-c0d1cece8d89">

Content padding and label padding look different?

**Comment by gimmixAT** [comment]
There are separate css variables in the `basti.scss` to control those padding so it looks like they where chosen un purpose. 
To unify them I woul maybe suggest reducing the padding on the header a bit and increase it in the cells to meet in the middle.

**Comment by rjahn** [comment]
Sounds like a plan.

**Comment by gimmixAT** [comment]
I adjusted the padding as suggested but also had to rework the CellEditor styling a bit because of that 6f2d3859284c4528eb61fdb9d70103ddaebecd70
