### ISSUE TITLE
Menu icon disappears on mouse-over

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#44]
The menu bar contains an icon in the collapsed and expanded state when I expand and collapse the menu bar using the menu button. When i expand the menu via mouse-over the icon disappears.

Collapsed menu bar with icon:
![20210126_1043 - Screenshot - React_App_-_menu 1 - collapsed](https://user-images.githubusercontent.com/77725044/105829899-2fcb9800-5fc5-11eb-88d0-e0127a9db2d0.png)

Expanded menu bar with icon:
![20210126_1043 - Screenshot - React_App_-_menu 2 - expanded](https://user-images.githubusercontent.com/77725044/105829972-3eb24a80-5fc5-11eb-8b40-e41389937464.png)

Menu bar expanded via mouse-over: no icon
![20210126_1044 - Screenshot - React_App_-_menu 3 - expanded mouse over](https://user-images.githubusercontent.com/77725044/105829985-4245d180-5fc5-11eb-9486-e81b527e630a.png)

Menu bar collapsed via mouse-out: no icon
![20210126_1044 - Screenshot - React_App_-_menu 4 - collapsed](https://user-images.githubusercontent.com/77725044/105829996-4540c200-5fc5-11eb-99c1-b20184e69155.png)

The icon appears again when I press the menu button.

**Comment by maximilianweidenauer** [comment]
fixed in 7a369b7914494b0e5bb2cda0888e9cdc686b85ae
Please test again when you have the next build.

**Comment by maximilianweidenauer** [comment]
Another fix in 9c0c25a27cc92c0891c5323b945ffb1839e1c307
