### ISSUE TITLE
tobpar is undefined

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#441]
Please check console errors like this one:

<img width="1401" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/e3f41d5b-192a-42d4-b250-be8607648920">

**Comment by gimmixAT** [comment]
This seems to be a timing issue when the app is first started and certain parts of the UI are rendered before the topbar which in turn causes an error which is wholy triggered by our code. I think we can remove that error since it isn't really of any consequence.

**Comment by rjahn** [comment]
OK, lets open a new issue if it's relevant.
