### ISSUE TITLE
screen resizable/closable/maximizable/iconifiable

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#443]
Currently a modal screen/content has default options: close, resize

It should be possible to change this default options. Server sends following boolean properties:

"screen_closable_"
"screen_resizable_"
"screen_iconfiable_"
"screen_maximizable_"

"content_closable_"
"content_resizable_"
"content_iconfiable_"
"content_maximizable_"

Please use what's supported. I don't know if maximizable/iconifiable are supported.

**Comment by maximilianweidenauer** [comment]
added support for closable, resizable and maximizable, iconfiable is not supported
