### ISSUE TITLE
Error without controls

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#444]
Add following code in MobileLauncher.java:

`if (true) throw new RuntimeException("ENDE");`

below super(....);

this will show:

(Safari)

<img width="673" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/92f795f6-4af6-4d2a-a2c0-5cf1c0028838">

(Firefox)

<img width="673" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/d645dfc0-0e23-48cb-8e7b-4a8d350f801b">

The gray line is missing?

The window is shown without close... This is good, but when do you hide close buttons ?

If no close buttons -> don't show a gray line and hide the button area below?

**Comment by gimmixAT** [comment]
the dialog footer is now ommitted if there are no exceptions to list

**Comment by rjahn** [comment]
style looks correct but why is there no OK button or another button? Usually such dialogs have a button?
Also it's not possible to close the dialog with X because there's no X.

So there must be some logic which disables closing?

**Comment by rjahn** [comment]
Did you change the style as well?

My error dialog now has a red header - which is correct?

<img width="630" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/e440a7cb-321a-433f-baac-31631fa236d6">

**Comment by gimmixAT** [comment]
Currently the OK button is only shown if the `appReady` flag is true which in this test case probably doesn't happen.
This was added due to #402

**Comment by rjahn** [comment]
okay, this makes sense!
