### ISSUE TITLE
Date cell editor re-opens automatically

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#445]
If you have a date cell editor -> open the popup with button -> click on a date -> popup re-opens automatically.
The selected value will be shown in textfield, but not sent to server -> not saved!

It's not possible to close the popup, only if you click in a free area outside the popup.

There's a problem with date selection!

**Comment by maximilianweidenauer** [comment]
So this is a tricky one, for some reason the DatePicker doesn't recognize, that the "day" element I'm choosing is a part of the content panel, so it thinks I'm clicking outside but I'm actually selecting a date. I have tested it with the demo on the PrimeReact Site and the don't have this issue, so I have to figure out why this happens, I've already tried commenting out a lot of configuration I did on the calender but nothing helped yet.

**Comment by maximilianweidenauer** [comment]
Okay now I'm getting the same issue on their demo site. I will create a PrimeReact Ticket
