### ISSUE TITLE
Login dialog does not fill in the last logged on user

### ISSUE THREAD

**Issue by mhandsteiner** [sibvisions/reactUI#449]
When opening the application again in a browser, the last logged on user from a previous session should be filled in, in case, the login dialog is opened, and the username and password is empty.
The first empty editor should be focussed initially, if the login screen opens. (if username is empty, the username field. if the username field is not empty, but the password field, is empty, then the password field. if both are filled, the logon button should be focussed)

**Comment by gimmixAT** [comment]
should be implemented now -> cdd19ed93e25faabe8bb6b23fde49d7f1e53a27f

**Comment by rjahn** [comment]
To test this, be sure that application.xml doesn't contain the username tag. Simply rename it

  <Application.Login.username2>x</Application.Login.username2>
  <Application.Login.password2>x</Application.Login.password2>

and also don't set username in config.json.
