### ISSUE TITLE
Mini layout: Expanded menu bar overlaps form

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#45]
When I resize my browser window and make it smaller, my form's layout changes from full to mini. 

If the menu bar is expanded during the resize, the menu bar works as expected: I collapse and expand the menu bar using the menu button and the form is shifted to the left / right so I  see the full content.

![20210126_1416 - Screenshot - React_App_-_mini layout - shift](https://user-images.githubusercontent.com/77725044/105849909-526baa00-5fe1-11eb-9fc4-fa903d7a3df0.png)

If the menu bar is collapsed during the resize, the menu bar overlaps the form when I expand it using the menu button.

![20210126_1416 - Screenshot - React_App_-_mini layout - overlap](https://user-images.githubusercontent.com/77725044/105849913-55669a80-5fe1-11eb-9c38-83e46fdd00ad.png)

(I do expect the overlap when I open the menu bar with mouse-over, this works correctly)

**Comment by rjahn** [comment]
Not clear what you want?

**Comment by dun-zilla** [comment]
I want the form to be shifted to the right when I press the menu button. Currently this only works as expected when I resize the form with an expanded menu bar and it does not work as expected when I resize the form with a collapsed menu bar.

**Comment by maximilianweidenauer** [comment]
I talked with René about this and I'm pretty sure we said that in mini mode the menu should always overlap.

**Comment by dun-zilla** [comment]
Well, it does neither always overlap nor always shift in mini mode.

**Comment by rjahn** [comment]
Mini mode should always overlap. It makes absolutely no sense to move the whole screen because the visible area is smaller than small!

The menu is temporary and shouldn't re-layout anything!
