### ISSUE TITLE
Focus cut off?

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#452]
Do we set overflow: false for panels?

The focus is not fully visible:

<img width="421" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/ff59bed6-5e42-4ce5-8eab-7da3eeddb4e7">

**Comment by maximilianweidenauer** [comment]
Yes overflow is false for panels thats why the focus is cut off

**Comment by rjahn** [comment]
But it shouldn't in general.

Only for: ScrollPanel, TabsetPanel, SplitPanel, Window/Frame

For simple Panels, the overflow should be visible.

We hade some changes in the past, looks like a wrong fix?

**Comment by gimmixAT** [comment]
This seems to have changed in b741e7291e614e9cf5a62d088f1e2b062378a67b -> what was the original problem there?
In which screen can I best reproduce this issue?

**Comment by rjahn** [comment]
also with Components screen -> click a radio button in the middle of the screen: Group-1 or Group-2

**Comment by gimmixAT** [comment]
> also with Components screen -> click a radio button in the middle of the screen: Group-1 or Group-2

In this case the hidden overflow is actually warrented because the parent RadioButtonGroupEditor / FlowLayout has autoWrap set to false. So in case there is an overflow that should be clipped.

**Comment by rjahn** [comment]
but it looks wrong from user point of view.

**Comment by gimmixAT** [comment]
overflow should be visible now in RadioButtonGroupEditor

**Comment by rjahn** [comment]
antoher problem: Calendar screen (user: feature):

<img width="292" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/ea2c047a-87ef-477e-b86a-63e52c26dcac">

**Comment by gimmixAT** [comment]
the focus render glitch on the Calendar screen should be fixed now as well

**Comment by rjahn** [comment]
Great. Is this fix a general fix or should we check other editors as well because it's a very specific fix for this component?
