### ISSUE TITLE
error dialog layout problem

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#453]
The text area is behind the table and if you select a record in the list, the message appears but behind the table?

<img width="613" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/d65968c8-3ee5-4ef2-9af9-6c8638e59d52">

**Comment by maximilianweidenauer** [comment]
Not happening for me in demo or "projekte" app

**Comment by rjahn** [comment]
Did you try with different mandatory columns? Maybe a problem with many records in the error dialog table.

**Comment by gimmixAT** [comment]
which browser / os did this happen?

**Comment by rjahn** [comment]
Will test this problem.

**Comment by rjahn** [comment]
the initial problem is not reproducable!

But there's a problem with message height:

without details:

<img width="599" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/a5b84eb5-fc1c-49e1-9e8d-72916ededeb9">


with details:

<img width="599" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/3079bd98-7aad-4204-9f4c-2367e4a00632">

The gap above the buttons grows?
