### ISSUE TITLE
Login as navigation target?

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#456]
If we login manually and press back, the login appears.

Do you logout automatically?
Login view shouldn't be a navigation target if we don't logout automatically!

**Comment by gimmixAT** [comment]
Is that going back behavior the status quo or the preferred one? Normally you should always be directed back to home.

**Comment by rjahn** [comment]
No its not the preferred one!
I tried to reproduce the problem but it's not that easy.

Sometimes it occurs if you're logged in an open some screens, navigate back and forward - open change password - and navigate back.

Sometimes, the login view appears. There must be a problem with history, but not trivial.
If login view appears an navigate forward was pressed - strange error messages occur.

So there is something wrong :)

Please try if it's possible to reproduce...

The login view shouldn never appear without user interaction or server-triggered.
Back navigation doesn't mean automatic logout, or do you have some code for automatic logout if login view is shown?

**Comment by gimmixAT** [comment]
That might sometimes happen if the back navigation isn't caught by the internal route handling.

I'll try to implement that after a successful login the next screen is not added to the history after but rather replaces the login screen.

**Comment by rjahn** [comment]
We should change the current handling!

**Comment by gimmixAT** [comment]
The code uses `replace` now instead `push` after login, this way the login screen can not be navigated to via the back button anymore

**Comment by rjahn** [comment]
Tried to reproduce and wasn't possible!
