### ISSUE TITLE
Toolbar style not nice

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#458]
<img width="95" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/71af3559-9e75-489f-8e9f-c035506d76dc">

Some gaps between buttons?

Too much gap after last button in group?

**Comment by gimmixAT** [comment]
This should be improved and / or fixed now. There were some problems with the position calculations with gaps between toolbar items

**Comment by rjahn** [comment]
your change removes the '--toolbar-gap' ?

**Comment by gimmixAT** [comment]
Technically yes but the toolbar gap was imho at the wrong place there anyway since that should be the gap between two toolbars and not between the children within a toolbar and therefore didn't work as intended to begin with. I'll look into fixing this next.

**Comment by gimmixAT** [comment]
I think the toolbar gap should be used correctly now

**Comment by rjahn** [comment]
Looks correctly!

**Comment by rjahn** [comment]
Is it possible to cherry pick changes to master_04_03_2024 branch?
