### ISSUE TITLE
NavigationTable: Content of password column is plain text

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#46]
The content of a column with datatype "Password" is displayed as plain text in a navigation table. (If I add an editor for that column to a form, the passwort is masked).

**Expected**: Passwords must always be masked with asterisk.

![20210129_1211 - Screenshot - TestApplication_-_Password in NavigationTable](https://user-images.githubusercontent.com/77725044/106269347-af0ed500-622c-11eb-8b7c-348a58904a8e.png)

**Comment by rjahn** [comment]
The information can be found in content-type of cell editor or metadata!

**Comment by rjahn** [comment]
The same problem as described in #55.
The default cellRenderer implementation is missing.
