### ISSUE TITLE
Layout of buttons wrong

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#462]
Top: swingUI
Bottom: reactUI

Buttons layout is wrong

<img width="385" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/2bac52eb-1f3f-4086-9589-b0208327f9e3">

**Comment by maximilianweidenauer** [comment]
Reproducer?

**Comment by rjahn** [comment]
Simply create a new screen in VisionX and add an image column?

**Comment by rjahn** [comment]
Not reproducable.

* Button size should be the same for all three buttons
* No tooltips

**Comment by rjahn** [comment]
changed stylesheets for button size and set delay for tooltips
