### ISSUE TITLE
setPreferredSize(0, 0) crash

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#468]
If you set the preferred size on a panel, the client crashes

**Comment by gimmixAT** [comment]
how best to reproduce this with JVx.mobile ?

**Comment by rjahn** [comment]
Will create a test screen for this (bug/bug user)!
My first test screen didn't throw any exceptions, so it must be trickier.
I'll update this ticket asap.

**Comment by rjahn** [comment]
I tried to reproduce the layout problem but I guess it's now  an endless loop. The test user: bug/bug
Test screen is: Preferred Size

Simply try to open it.

The PreferredSizeWorkScreen has two modes with two endless loops:

  int iBugNumber = 1;

or

  int iBugNumber = 2;


I have a demo application for the initial bug, but it's a VisionX application.

**Comment by rjahn** [comment]
the initial size is maybe related to split panel...

**Comment by gimmixAT** [comment]
the example seems to work now in 3bb558451974c7ccaadf0a171181fcba1ace96e2

**Comment by rjahn** [comment]
no more problems with fix
