### ISSUE TITLE
loading indicator shown inside linked cell editor

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#477]
Not always a good idea to show the loading indicator inside the editor 

![image](https://github.com/sibvisions/reactUI/assets/1307043/635d91a1-47b3-40dd-961b-b956be827b72)

**Comment by gimmixAT** [comment]
I tweaked the styling for this a bit, the spinner is now on top of the button and hides the chevron

**Comment by rjahn** [comment]
Works great and is smooth.
