### ISSUE TITLE
horizontal alignment of hyperlink is not working

### ISSUE THREAD

**Issue by rolandhoermann** [sibvisions/reactUI#481]
Use a Hyperlink and set horizontal alignment to left. It's still centered.

**Comment by gimmixAT** [comment]
@rjahn I was able to reproduce this by adding `link.setHorizontalTextPosition(0);` in `HyperlinkWorkScreen.java`

Possible fix in 82cf9c0556129789fce4becdb51a1cbf18dc2a3c

**Comment by rjahn** [comment]
horizontalTextPosition was the wrong property, because it's the position beside an icon.

horizontalAlignment is right.
ComponentsWorkScreen is now correct.

**Comment by rjahn** [comment]
In my test, horizontalTextPosition(0) also didn't work. 
Anyway.

To align, we have to set:

```
display: block
text-align: left | right | center
```

for the `hyperlink-wrapper > a`

**Comment by rjahn** [comment]
and also the height of the hyperlink component is now smaller than before.

The trick: it was handled like a button

**Comment by rjahn** [comment]
My mistake! Forgot to pull.

setHorizontalAlignment(IAlignmentConstants.ALIGN_LEFT) is workind and also ALIGN_RIGHT

But in Components screen, the height has changed with your update? Before your update it had the same height like a button. Now it's only the text.

The height should be the same as before!

**Comment by rjahn** [comment]
padding: 0 is new.

```
padding-left: 0
padding-right: 0

```

because top and bottom are relevant

**Comment by gimmixAT** [comment]
the padding is now set via css and the p-link-button class
