### ISSUE TITLE
toggle button styling wrong

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#488]
Component screen

first button is a toggle button, but the paddings are wrong compared to other buttons?

**Comment by gimmixAT** [comment]
looks like the DOM might have changed a bit on this PR component and now our styles don't apply correctly anymore. Will compare with `master_04_03_2024`

**Comment by gimmixAT** [comment]
As I thought there seem to have been some changes. Probably for accessibility.
I tried refactoring the styles & props and it seems to look ok now. Are there any other screens with variations of the toggle button?

**Comment by rjahn** [comment]
DirectCellEditor screen has two toggle buttons, but look good now!
