### ISSUE TITLE
Morph Panel: Display Mode Popup not supported

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#49]
When I want to open the popup of my MorpPhanel in Display Mode "Popup", nothing happens.

![20210129_1252 - Screenshot - TestApplication_-_Morph Panel - Popup](https://user-images.githubusercontent.com/77725044/106272745-d5833f00-6231-11eb-8409-722fe2c48b20.png)

**Comment by rjahn** [comment]
The 

> Details> 

button has no gaps? Please compare the screen to vaadinUI and swingUI... There should be a small gap between the top and right border of the screen?

**Comment by maximilianweidenauer** [comment]
So in the demo I changed the Contacts workscreen to popup. At first I set tabHeaderVisible false and when I selected a datarow I expected to get a similiar response to the demo popup screen. Instead I received "visible: true" for a panel which is already visible. Uploading the response when selecting a row and the already visible panel.
![image](https://user-images.githubusercontent.com/66732863/117673597-37e1c900-b1ab-11eb-9d1a-e6a9ddb4718f.png)

![image](https://user-images.githubusercontent.com/66732863/117673762-5a73e200-b1ab-11eb-895d-75a5c4e76314.png)

**Comment by maximilianweidenauer** [comment]
When I set tabHeaderVisible: true, it showed the "Details" button like in @dun-zilla's screenshot, but when I selected a datarow and clicked it, I receive a "normal" selectRow response
![image](https://user-images.githubusercontent.com/66732863/117674084-a888e580-b1ab-11eb-8b76-ece4a810456c.png)

And again a visible: true for the already visible panel at the pressedButton response

![image](https://user-images.githubusercontent.com/66732863/117674272-d1a97600-b1ab-11eb-8478-611d93d03e43.png)

![image](https://user-images.githubusercontent.com/66732863/117674328-dcfca180-b1ab-11eb-9de1-988a149ae795.png)

**Comment by maximilianweidenauer** [comment]
Popups worked when #193 was done... now the last problem was that closeContent didn't work properly which is now resolved so this is done aswell!
