### ISSUE TITLE
popup outside of visible area

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#492]
screen: Contact Error (DB)

Press the right menu button...
The popup menu is cut of because it's outside the visible area. Is there an option to show the popup fully?

<img width="1168" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/ca4bb48c-ec26-4a29-881b-4bb9ac887a0b">

**Comment by gimmixAT** [comment]
should be fixed, the position is already corrected per default but there was some custom positioning code that messed with that
