### ISSUE TITLE
Error popup styling

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#494]
Open Contacts Error (DB) and try to change the selected record:

Safari:

<img width="798" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/b3818fa5-f863-448c-b936-344b086e5cfb">

Chrome:

<img width="798" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/fee46bba-eee7-4141-ac2a-6cd2f3adfa65">

Safari shows a small line above buttons (until you move the window) and Chrome doesn't show the line.
Both browsers show round gray corners:

<img width="448" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/09e109a7-6275-4e54-9ab8-2a528e432709">

So there's something wrong!

The desktop UI:

<img width="575" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/293e622f-a2b5-41c2-a430-a2cb9635435a">

There's no gray line.

If you test with Messages screen and open the Information:

<img width="505" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/8f5e9d8c-ffde-4f19-9b23-36218b132ecf">

looks in react UI:

<img width="470" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/b83a4249-7130-417c-b253-d34fcb738b57">

So there's something wrong with styling, because:

Error popup has shadow in header, messages doesn't have such shadow. Error popup has big paddings, message doesn't use the same padding.

With Messages screen, you can test both, with Button:

* Fehler
* Error (closed)

**Comment by rjahn** [comment]
the error dialog paddings are not good enough, because the right padding is not the same as the left? buttons vs. icon...

**Comment by gimmixAT** [comment]
There also seems to be a difference between an actual error (e.g. in `Contacts Error`) and the Error styled Dialog in the `Messages` screen.

I'd suggest the following adjustments:

- [ ] always have icon in the the header to the left of the title
- [ ] haromnize paddings
- [ ] harmonize visual lines e.g. same distance to left in dialog title and body

**Comment by gimmixAT** [comment]
the styling of the two different error dialogs should be harmonized now
