### ISSUE TITLE
focus not shown

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#499]
If you press a button in screen `DynamicImage`, the top and bottom focus is cut. I guess it shouldn't? 

<img width="437" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/6564b4c9-db81-483f-85f5-90deee66fdcd">

**Comment by gimmixAT** [comment]
the clipping should be fixed now in this case, I switched top clip instead of `overflow:hidden` which allows for additional padding in the clipping mask so that the focus isn't clipped.
