### ISSUE TITLE
Restart problem

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#503]
Be sure that autologin is disabled for the application!

Start server and open reactUI -> session starts
login with valid username and password
Restart server
-> Session expired banner appears and click
login appears
try login with valid username but wrong password
-> APPLICATION restarts?
login appears
try login with valid username and wrong password
-> no more problems

looks like a session cache problem if we press the banner?

**Comment by gimmixAT** [comment]
@rjahn I can't seem to get JVx.mobile not to auto login. The option (`Application.Login.autologin`) in the `application.xml` is set to `false` and I removed the credentials from the `config.json`

**Comment by rjahn** [comment]
Do you use config.json in your react UI? Please check if there's a username/password?

**Comment by gimmixAT** [comment]
@rjahn Removing the credentials from the appication.xml seems to have done the trick. I can't really reproduce the described behavior though. The application does restart but after clicking the banner which seems to be intended. If I login with wrong credentials afterwards I just receive an error dialog for a wrong password but no restart occurs.

Would it make sense to update JVx.mobile to the latest version in case this is an issue that just recently got introduced?

**Comment by gimmixAT** [comment]
The behavior in FF vs. Chrome was a bit different regarding when the error for the exit command failing would be triggered. Since it was unhandled so far it might have caused code not being executed in Chrome. Maybe try if it works now with 076f5df018fdbb79830cabc8c68a9975304a93d4

**Comment by rjahn** [comment]
No more problems.
