### ISSUE TITLE
Error dialog problem (no OK button)

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#504]
Try manual login with valid username and invalid password.

The error appears:

<img width="610" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/cbee902d-e76d-46d1-a1ad-5940dae20ec3">

OK button is missing!

In "old" version (master_04_03_2024) the OK button was available but with wrong styling:

<img width="620" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/6e80d990-f0ed-4dca-b60d-ac46e0edd6ed">

hover:

![image](https://github.com/sibvisions/reactUI/assets/1307043/2f84abdc-d867-4ea7-99e9-5faffb24bac5)

Please fix the styling in old master (styling) and show the button bar in master.

Maybe related to #444 and #503?

**Comment by gimmixAT** [comment]
The missing button in `master` is fixed. I wasn't able to reproduce the styling error in `master_04_03_2024` though.

**Comment by rjahn** [comment]
maybe a local css cache problem with master_04_03_2024.

In current version, Safari shows a gray line:

<img width="617" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/93be2f49-84ef-4a4b-ab01-5fd0b6f3820d">

but Chrome or FF don't show the line.

And if  I move the dialog in Safari, the line is hidden.

**Comment by gimmixAT** [comment]
I added some css that should mitigate this. The line is probably a rendering glitch on retina screens or with screen scaling

**Comment by rjahn** [comment]
Safari (16.6):

https://github.com/user-attachments/assets/48cec8f8-4a19-45b2-b6a2-dbd61fe4219b

**Comment by rjahn** [comment]
You're right - it's a broswser rendering problem, but we could fix it by fixing another problem.

The border radius is set on top and bottom div tags. If you change the radius to e.g. 20px, it will look like:

<img width="393" alt="image" src="https://github.com/user-attachments/assets/f5e94faf-9d67-4b09-9129-5762ae4cdc30">

because the box-shadow is set for the rc-message dialog div. 
It's important to set the border for the main div as well!

And if we set this, we could set the background-color to white, which will fix the problem with rounding/rendering problems, e.g.:

```css
background-color: white;
border-bottom-left-radius: var(--dialog-border-radius);
border-bottom-right-radius: var(--dialog-border-radius);
border-top-left-radius: var(--dialog-border-radius);
border-top-right-radius: var(--dialog-border-radius);
```

**Comment by gimmixAT** [comment]
I added the background to the general dialog element and fixed the missing use of the dialog-border-radius variable

**Comment by rjahn** [comment]
Everything is working!
