### ISSUE TITLE
code style configuration

### ISSUE THREAD

**Issue by fls-indinf** [sibvisions/reactUI#507]
Hi fellow engineers!

In order to streamline code collaboration and style consistency, would you like to share your settings for the code formatter plugin you use?

In VSCode I by using Prettier and  put this into my .prettierrc to persist the style for my team:
```json title=".prettierrc"
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false,
  "trim_trailing_whitespace": false,
  "printWidth": 200
}
```

I discovered recently a cross-editor configuration format (https://editorconfig.org/) - in case you don't use VSCode or a compatible formatter.

**Comment by rjahn** [comment]
We don't use specific code formatters. Only standard settings. We work with VSCode.
