### ISSUE TITLE
LinkedCellEditor shows no records

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#510]
User: features
Screen: Lazy loading

Both linked cell editors are empty if you press the arrow button

**Comment by rjahn** [comment]
the filter response contains values, but popup is empty

**Comment by gimmixAT** [comment]
this should be fixed now

**Comment by rjahn** [comment]
popup now shows values, but the cell renderer is not right?

See swing UI:

<img width="288" alt="image" src="https://github.com/user-attachments/assets/cb564264-feb7-4c11-82be-1fd3a8a3c31f">

It's also working in flutter UI

<img width="371" alt="image" src="https://github.com/user-attachments/assets/057900d0-a7af-4f26-a8eb-4fb93d64fe39">

**Comment by gimmixAT** [comment]
the coice & checkbox widget should get rendered now in the linkedcelleditor 055f6c3ae6caaa8f751956ffffb7456c8bb0f846

**Comment by rjahn** [comment]
renderer is working, but lazy loading stopped working. The editor shows 99 records in my case, but doesn't load more.

**Comment by rjahn** [comment]
works perfect
