### ISSUE TITLE
UIEditorLinked does not format date columns

### ISSUE THREAD

**Issue by fls-indinf** [sibvisions/reactUI#515]
Given a LinkedCellEditor in a application:
![image-2024-06-20-11-13-00-780](https://github.com/user-attachments/assets/d184f9e1-a538-42e5-be3d-1bddc76ca91b)
the LinkedCellEditor/UIEditorLinked just displays the date of birth as number:
![image-2024-06-20-11-13-21-574](https://github.com/user-attachments/assets/6200716e-0028-4846-bf06-c7677b87d51c)

**Comment by rjahn** [comment]
Do you work with live repo?

**Comment by rjahn** [comment]
maybe related to #510 because we fixed showing choice cell renderers

**Comment by fls-indinf** [comment]
A brief simplified version to test the issue:

```java
public class SimpleWorkScreen extends DataSourceWorkScreen {

  private IDataBook db;
  private IDataBook linked;

  public SimpleWorkScreen(IWorkScreenApplication pApplication, AbstractConnection pConnection) throws Throwable {
    super(pApplication, pConnection, null);
    initializeModel();
    initializeUI();
  }

  private void initializeModel() throws Throwable {

    RowDefinition rdLinked = new RowDefinition();
    rdLinked.addColumnDefinition(new ColumnDefinition("KEY", new StringDataType()));
    rdLinked.addColumnDefinition(new ColumnDefinition("DATE", new TimestampDataType(new UIDateCellEditor("dd.MM.yyyy hh:mm"))));
    linked = new MemDataBook(rdLinked);
    linked.setName("linked");
    linked.open();

    linked.insert(false);
    linked.setValues(rdLinked.getColumnNames(), new Object[] {"KEY", new LocalDateTime().toDate().toInstant().toEpochMilli()});
    linked.saveAllRows();

    UILinkedCellEditor ce = new UILinkedCellEditor(new ReferenceDefinition("TEST", linked, "KEY"));

    RowDefinition rd = new RowDefinition();
    rd.addColumnDefinition(new ColumnDefinition("TEST", new StringDataType(ce)));

    db = new MemDataBook(rd);
    db.setName("db");
    db.open();

    db.insert(false);
    db.setValues(rd.getColumnNames(), new Object[] {"KEY"});
    db.saveAllRows();

  }

  private void initializeUI() throws Throwable {
    setLayout(new UIBorderLayout());

    UITable table = new UITable();
    table.setDataBook(db);

    add(table, IBorderLayout.CENTER);
  }
}
```

**Comment by gimmixAT** [comment]
I just changed the cell rendering behavior in LinkedCellEditor suggestions popup. Please try if dates are rendered correctly now.

**Comment by rjahn** [comment]
Test screen is now available in mobile project for user: bug and Screen name: Date in LinkedCED

**Comment by fls-indinf** [comment]
![grafik](https://github.com/user-attachments/assets/674b88bd-3520-4b66-bf47-4776a987b28d)
Thank you for your late-night fix 🎉 It seems to work overall fine!

The only, maybe a bit weird behavior is when only one row is in the autosuggest.
![grafik](https://github.com/user-attachments/assets/bb81bc8a-e893-409b-a2ba-2870fcd1eacd)
When scrolling, the entry disappears and a "blank" row appeared.

**Comment by gimmixAT** [comment]
@rjahn the header is currently shown or not based on the `cellEditor.tableHeaderVisible` flag which in this case is false

**Comment by gimmixAT** [comment]
the empty line in the suggestions should be gone now -> e8cb88dad6feae6e6227984374d3e2d2f4223319

**Comment by rjahn** [comment]
@fls-indinf any feedback for us?

**Comment by rjahn** [comment]
Nice info, because you didn't write anything about "enabling table Header". It was my comment that it's different.

**Comment by fls-indinf** [comment]
@rjahn yes, you are right. 👍

I just wanted to try it, so I added a column to also test it with enabled table headers, since you mentioned it. 😉

**Comment by rjahn** [comment]
You closed this ticket, but do you create a new ticket for the scroll problem?

**Comment by fls-indinf** [comment]
@rjahn sry, would you have preferred it to be resolved in this issue?
I don't know how you would like to address this usually. 

Do you usually try to separate the concerns of tickets (a bit like in the oss ticketsystem) or would you like to keep it on only one, to have one stream of context?
