### ISSUE TITLE
UICheckBoxCellEditor doesn't display the checked state

### ISSUE THREAD

**Issue by fls-indinf** [sibvisions/reactUI#516]
In Vaadin the editor correctly displays the current state in the datarow, when the value matches the predefinded checked value:
![grafik](https://github.com/user-attachments/assets/1c015546-b943-4b73-8736-e1e3e961de2b)

In React the Checkbox is allways uncheckd and can't be checked by cklicking it:
![grafik](https://github.com/user-attachments/assets/ccd8d9f8-7d6d-4956-b2d6-06742f9d4755)

The Workscreen I used is this one (I also added a UIEditor afterwards):
```java
public class SimpleWorkScreen extends RemoteWorkScreen {

  private IDataBook db;

  public SimpleWorkScreen(IWorkScreenApplication pApplication, AbstractConnection pConnection) throws Throwable {
    super(pApplication, pConnection, null);
    initializeModel();
    initializeUI();
  }

  private void initializeModel() throws Throwable {

    RowDefinition rd = new RowDefinition();
    rd.addColumnDefinition(new ColumnDefinition("UNCHECKED", new BigDecimalDataType(new UICheckBoxCellEditor(BigDecimal.ONE, BigDecimal.ZERO))));
    rd.addColumnDefinition(new ColumnDefinition("CHECKED", new BigDecimalDataType(new UICheckBoxCellEditor(BigDecimal.ONE, BigDecimal.ZERO))));

    db = new MemDataBook(rd);
    db.setName("checkboxdb");
    db.open();

    db.insert(false);
    db.setValues(rd.getColumnNames(), new Object[] {BigDecimal.ZERO, BigDecimal.ONE});
    db.saveAllRows();

  }

  private void initializeUI() throws Throwable {
    setLayout(new UIBorderLayout());

    UITable table = new UITable();
    table.setDataBook(db);

    add(table, IBorderLayout.CENTER);

    UIEditor e = new UIEditor(db, "CHECKED");
    add(e, IBorderLayout.NORTH);
  }
}
```

**Comment by rjahn** [comment]
Sure, it's not what you want but did you try boolean data type?

**Comment by fls-indinf** [comment]
> Sure, it's not what you want but did you try boolean data type?

![grafik](https://github.com/user-attachments/assets/c90c28ce-51eb-4732-b4c4-89ac675095cb)
Boolean seems to work.

**Comment by rjahn** [comment]
I guess our react checkbox implementation doesn't use the select/deselect value correctly and always converts boolean values? The server sends selectedValue and deselectedValue and this objects should be used for setValue requests. I will create a test screen.

**Comment by rjahn** [comment]
Test screen is available in mobile demo application with user: bug and Screen: Check Box

**Comment by gimmixAT** [comment]
@rjahn thanks for adding the test screen

In the case of the big decimal, the data is sent by the server as string in the `selectedRow` coming from `dal.fetch` and as number in the `cellEditor.selectedValue` which results in a mismatch and therefore is always unchecked.

I added a change that converts the values to strings before comparing them, which in this case works. Is there also the possiblity of setting complex data like objects as possible values or is it always values that have a proper string representation.

**Comment by rjahn** [comment]
Not sure why there's a string for the column. It should be a number. Will check this.
The column is defined as "number" by BigDecimalDataType and the values are also number (BigDecimal.ONE, BigDecimal.ZERO). I will check the server-side.

Only simple/primitive datatypes are supported. No complex data.

**Comment by rjahn** [comment]
sending numbers as strings is correct....

The client sends option_bigdecimal_as_string: true in startup request.

This means that all "big decimals" will be sent as strings. Please check where the client requires this option. I guess it's because of floating point precission.

Server could send numbers without decimal points as numbers... 
You should convert decimals to string in case of option_bigdecimal_as_string. You know that it's a number cell with dataTypeIdentifier in metadata.

**Comment by rjahn** [comment]
string compare should be fine in this case.
The problem was floating point precission: 1002.341 -> 1002.3410000000000081854523159563541412353515625

So we send "1002.341" and it's fine.

**Comment by gimmixAT** [comment]
is there some information in the server response on how to format the number when converting to string? Ideally the `cellEditor.selectedValue` would also be a string in this case. I'll convert it on the client side in any case with the information you provided in your previous comment

**Comment by gimmixAT** [comment]
the string comparison is now only used in case of BigDecimal values

**Comment by rjahn** [comment]
Currently, we don't send selectedValue or unselectedValue as string, because the object is used in UI and the developer expects numbers. In case of records, it's easier to convert values.

We could change selectedValue before transmission, but it's not necessary if we compare strings - which is a good solution anyway

**Comment by rjahn** [comment]
Client should send a number to the server in setValues, not a string. So it's better so keep the BigDecimal without string conversion.
