### ISSUE TITLE
UIEditorLinked scrolls to bottom without data in the edited cell

### ISSUE THREAD

**Issue by fls-indinf** [sibvisions/reactUI#517]
When enabling the TableHeader, it scrolls to the bottom of the suggestions, when the editor is empty:
![grafik](https://i.imgur.com/rOdoJsm.gif)
(Edit: Making the data in the "KEY" column distinct didn't change the behaviour)

_Originally posted by @fls-indinf in https://github.com/sibvisions/reactUI/issues/515#issuecomment-2498194930_

**Comment by rjahn** [comment]
the height calculation should recognize table header. If you have at least 2 records and the table header visible, scrollbars shouldn't be needed.

**Comment by gimmixAT** [comment]
the jumping as well as the inadequate height should be fixed now

**Comment by fls-indinf** [comment]
Great job!
It looks pretty awesome so far!
![grafik](https://github.com/user-attachments/assets/076609a5-73de-4005-b916-4fa3669efd0a)
