### ISSUE TITLE
Insert new record not working

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#522]
User: features
Screen: Simple Contacts (DB)

Press: New (empty)

<img width="527" alt="image" src="https://github.com/user-attachments/assets/e3b47eb1-00a5-4924-b27a-d50ebc33abad">

Inserts also a new line at the end of the table

**Comment by gimmixAT** [comment]
should be fixed by 50e1c26670ebb535e46fcdd4d7dd665d3db2559e
