### ISSUE TITLE
table with outside-record click not clear for user

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#524]
User: features
Screen: Contacts (DB)

click one record -> shows details -> click Cancel/Abbrechen button

click outside the records -> under the last record -> also shows details of current selection

This click outside the records is unusual/unclear for a user.

**Comment by gimmixAT** [comment]
This navigation is triggered by a mouseRelease event sent on the table `Con-CG_NT_contacts`

Should those mouse events only be triggered when interacting with the data rows?

**Comment by rjahn** [comment]
only click on records should send a selectRecord request
if a eventClicked, eventPressed, eventReleased is set for the component, also send the event outside of record area

BUT, this is the behavior right now and it's the same in swing!

If possible, please could you send additional properties in mouse events: onSelectedCell (boolean), onSelectedRow (boolean)

onSelectedCell means click on selected row and selected column
onSelectedRow means click on selected row (anywhere)

onSelectedRow and onSelectedCell should be true in case of event on selected cell

both only can be true if event fires on record area

**Comment by gimmixAT** [comment]
the flags should be sent now with mouse events on a UITable -> 858754bceebe8b44ebb24bfef8d56e297b234dcf

**Comment by rjahn** [comment]
your handling is not correct because if you click on an unselected record, onSelectedRow is false, but should be true.
The selectRecord event is sent before mousePressed....

**Comment by gimmixAT** [comment]
I didn't change anything about the order in which events are sent. So I take it the order should be as follows?

- mousePressed
- mouseReleased
- focusGained
- selectRecord

Regarding the onSelectedRow being false, I am a bit confused as to how this should be set -> so for my understanding, what is the variable supposed to express? That the user clicked on a selected row or that the row should be selected? Or something else altogether.

Right now it behaves like you described here: https://github.com/sibvisions/reactUI/issues/524#issuecomment-2530682508
-> if you click on a selected row `onSelectedRow: true` if it is an unselected row: `onSelectedRow: false`

**Comment by gimmixAT** [comment]
Yes this is mostly a timing problem, the events are handled in a different order in the client then they are sent. 
I changed it so that the flags are `true` now even if the Row / Cell are not technically selected yet but are selectable, so most likely will be selected

**Comment by rjahn** [comment]
Looks great, but one optimization if you also think it makes sense:

onSelectedCell should be true, only if row was selected and column was selected.
Currently, onSelectedCell and onSelectedRow are true - always together.

The onSelectedRow handling is perfect because we send selectRecord events before mouse events and expect a selected record in the mouse events. The right column is already selected in the mouse event, but we should have the information if user clicked on an already selected cell or selects a new cell.

I guess this makes sense?

**Comment by gimmixAT** [comment]
I changed it so that onSelectedCell will only be true if the cell was already selected. 
The handling of this can definitley be improved in the future by e.g. waiting for the initial select to return and hold click event requests until then so we can set those flags more correctly.
