### ISSUE TITLE
Insert new record - wrong row height

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#526]
Insert a new record in a table, e.g Contacts (DB) - Education

The row height is wrong:

<img width="525" alt="image" src="https://github.com/user-attachments/assets/b91edfa1-8fc1-4124-83a2-67d5f021e142">

**Comment by gimmixAT** [comment]
this was also due to the new roheight behavior which is now behind a feature flag -> #173 

if the flag is enabled now it should now also take into account the row height set via the css theme so an empty row shouldn't collapse anymore
