### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#53]
My locale is english.
The decimal symbol for datatype "currency" is not correct in editors (should be "."):

![20210129_1404 - Screenshot - TestApplication_-_Google_Chrome_150](https://user-images.githubusercontent.com/77725044/106278467-09169700-623b-11eb-9624-3112c17ec288.png)

The navigation table's renderer does use the correct decimal symbol:

![20210129_1404 - Screenshot - TestApplication_-_Google_Chrome_149](https://user-images.githubusercontent.com/77725044/106278501-16cc1c80-623b-11eb-9fc8-41b530ab1543.png)

The thousands separator is not displayed neither in the editor nor by the table's renderer.

**Comment by rjahn** [comment]
The format is set in the cellEditor definition.

**Comment by maximilianweidenauer** [comment]
Aside from the problem with the thousand seperator, PrimeReact currently has a bug with their fractional inputs e.g. you have a value 100,5, then you delete the ",5" part, you can't write a comma or dot again... https://github.com/primefaces/primereact/issues/1768
They added the linked ticket to the milestone 6.1.0 so we will have to wait until then for this part of the problem.
