### ISSUE TITLE
Inspect password not supported

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#54]
The editor of passwords shall contain an "inspect passowrd" feature that allows the user to temporary see the password.

![20210129_1423 - Screenshot - TestApplication_-_Google_Chrome_154](https://user-images.githubusercontent.com/77725044/106280037-a7a3f780-623d-11eb-9ffc-ac1c3e6859f2.png)

VisionX:

![20210129_1423 - Screenshot - TestApplication_156](https://user-images.githubusercontent.com/77725044/106280053-ad99d880-623d-11eb-9fb1-39aab03a3834.png)

**Comment by rjahn** [comment]
This is a special control and should work out-of-the-box without additional work.

The component: PasswordEditor is a panel which contains an editor and a button.
If you hide the button, the panel is removed and only the editor is used....

But if you see the button in swingUI or vaadinUI, you should see it in reactUI as well!

**Comment by rjahn** [comment]
Please test with latest server version again!

**Comment by maximilianweidenauer** [comment]
Server fix for #58 also fixed this issue
