### ISSUE TITLE
Navigation Table: Image rendering not supported

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#55]
For columns with datatype "image", the byte content is rendered instead of the image. 
The editor contains the hard-coded text "Iam a Dummy".

**Comment by rjahn** [comment]
We use following mechanism:

Every column has a cellEditor and a CellRenderer. The Editor is responsible for data manipulation and the renderer shows the value. Every cellEditor is also a cellRenderer in our swing/vaadin default implementation.

The table and tree implementations use the cellRenderer... and cellEditor (if record manipulation is possible)
A simple Editor doesn't need a cellRenderer, only cellEditor

The developer usually sets only the cellEditor... It makes no sense to define cellEditor and cellRendere again and again. Its just faster to use "default" implementations.

Our table/tree implementation checks following:
Is there a renderer ? 
Yes -> use it
No -> check if cellEditor is also a cellRenderer -> use it
