### ISSUE TITLE
Toggle Button: State not visible

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#56]
A Toggle Buttons shall be displayed differently when toggled. 
Currently the button is always light grey, toggled or not.

![20210129_1433 - Screenshot - TestApplication_-_Google_Chrome_157](https://user-images.githubusercontent.com/77725044/106281029-f30ad580-623e-11eb-9eac-59b07bb60291.png)

**Comment by rjahn** [comment]
Looks disabled also.

**Comment by dun-zilla** [comment]
> Looks disabled also.

Maybe that's the problem, I never toggled it because it is disabled? But it is actually focusable and a disabled control should never receive the focus, should it?

**Comment by rjahn** [comment]
No, makes no sense to give the focus to a disabled component.

**Comment by maximilianweidenauer** [comment]
Currently working on this one... No it's not disabled... I was assuming that I should only update based on props.selected... And for the colors I'm using the default-color used in Vaadin because I didn't know how I should display a selected button. 
![image](https://user-images.githubusercontent.com/66732863/106439517-0fde1d80-6478-11eb-8622-513221215d69.png)
Left one is not selected right one is selected

**Comment by maximilianweidenauer** [comment]
Selected is a gradient which looks like a button pushed in... Copied that straight out of Vaadin.

**Comment by maximilianweidenauer** [comment]
Nevermind the color is a bit darker than Vaadin I can adjust that or change entirely if you want to.

**Comment by rjahn** [comment]
Oh. Lets change the default color to the default button color... blue in our case?

Selected -> try use a different border and a darker/brighter default color...

Selected state?
Do you send the pressed event to the server?

**Comment by maximilianweidenauer** [comment]
I'm sending the pressButton event to the server. The buttons in e.g. JVxTraining then reply with a new selected property, but the buttons in the demo send no properties at all...
Currently I'm sending the pressButton like this:
![image](https://user-images.githubusercontent.com/66732863/106441672-a3185280-647a-11eb-9dd0-1cb285cf1f3e.png)
Do I need to send the selected-state in the pressButton as well?

**Comment by maximilianweidenauer** [comment]
I was a little confused about that. The buttons in JVxTraining sent a property while others didn't so i thought that if the action isn't coded in VisionX, nothing should happen.

**Comment by rjahn** [comment]
Looks like a problem on server-side. The selected state is not changed!

**Comment by rjahn** [comment]
Please update server implementation and try again the state change.

**Comment by maximilianweidenauer** [comment]
It works! Now I'm receiving the state change.
