### ISSUE TITLE
Responsive Layout: Combobox error

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#58]
My layout consists of two columns in full mode. When switching to mini mode, my combobox is not correctly layouted and cause the layout to be corrupted. The problems occurs only with comboboxes .

Open the workscreen in full mode:

![20210201_1011 - Screenshot - TestApplication_-_Google_Chrome_162](https://user-images.githubusercontent.com/77725044/106437831-f9cf5d80-6475-11eb-8227-724998a1323c.png)

Change to mini mode:

![20210201_1011 - Screenshot - TestApplication_-_Google_Chrome_163](https://user-images.githubusercontent.com/77725044/106437858-02279880-6476-11eb-9e7f-66d6da55d1e3.png)

When I initially open the workscreen in mini mode, the layout ist ok:

![20210201_1011 - Screenshot - TestApplication_-_Google_Chrome_164](https://user-images.githubusercontent.com/77725044/106437880-081d7980-6476-11eb-9618-1f471ce2cb55.png)

It gets corrupted when I switch to full mode:

![20210201_1012 - Screenshot - TestApplication_-_Google_Chrome_166](https://user-images.githubusercontent.com/77725044/106437916-1075b480-6476-11eb-8de3-8ca8558f858b.png)

**Comment by maximilianweidenauer** [comment]
When switching wether from full to mini or from mini to full, the Combobox doesn't receive new properties from the server... (e.g. new constraints). However, when you uncheck "Bearbeiten Button anzeigen" in VisionX, you receive new properties from the server!

**Comment by rjahn** [comment]
the "edit button" is the small button beside the combobox. This button isn't visible in above screenshots..

When switching, all constraints should be available? This is already working with simple editors?

The ComboBoxEditor is a special editor: If "edit button" is visible, the editor is wrapped as Panel, which means that the panel has a layout and constraints...
If "edit button" is not visible -> editor is a editor without panel around....

The constraints of editor are not layout constraints of outer layout!

**Comment by maximilianweidenauer** [comment]
The button should be visible now but I don't get a panel or a button for the combobox
![image](https://user-images.githubusercontent.com/66732863/107344470-c79bac80-6ac2-11eb-8159-99a2b740008c.png)
Should be around "E1209"

**Comment by maximilianweidenauer** [comment]
And when switching devicemode, the two labels and the text editors do get their new properties. 
![image](https://user-images.githubusercontent.com/66732863/107344960-5c060f00-6ac3-11eb-9919-cdc2b4bd19cb.png)

**Comment by rjahn** [comment]
currently not supported by JVx.mobile - will change this.

**Comment by rjahn** [comment]
Not sure, but the initial description didn't tell us about "hidden edit button". If edit button is hidden, it should be similar to a standard editor.

Try to replace ComboBoxEditor with UIEditor (in Source Code) and the only difference should be the edit button...

**Comment by maximilianweidenauer** [comment]
Yeah when I do that everything works as expected. The initial description didn't tell us about "hidden edit button", but I figured while I was doing some testing that this is the cause of this issue... When it is a ComboBoxEditor, I don't receive the panel and button and when changing devicemode no new constraints or any props.

**Comment by rjahn** [comment]
Okay, so did you try with latest VisionX?

This is now the response for such an Editor:

```
P94 (Panel)
 |- E96 (Editor)
 |- B95 (Button)
```

```json
[
  {
    "id": "P94",
    "name": "MorPanTes-8R_CBE_morphpaneltest_TYPE_TYPEN-wrapper",
    "className": "Panel",
    "classNameEventSourceRef": "ComboBoxEditor",
    "style": "comboboxeditor",
    "layout": "FormLayout,0,0,0,0,5,5,3,3",
    "parent": "P92",
    "indexOf": 1,
    "layoutData": "bm,b,-,0,0;r,-,-,0,0;l,-,-,0,0;l-1,rm,-,a,0;t,-,-,0,0;lm,l,-,0,0;b,-,-,0,0;tm,t,-,0,0;rm,r,-,0,0;r-2,l-1,-,-5,-5",
    "constraints": "tm;l1;b0;r1"
  },
  {
    "id": "B95",
    "name": "MorPanTes-8R_B_DOOPENEDITOR",
    "className": "Button",
    "focusable": false,
    "image": "FontAwesome.book;mapping=true,17,17,false",
    "eventAction": true,
    "parent": "P94",
    "visible": true,
    "text": "",
    "enabled": true,
    "indexOf": 0,
    "constraints": "tm;l-1;bm;rm"
  },
  {
    "id": "E96",
    "name": "MorPanTes-8R_CBE_morphpaneltest_TYPE_TYPEN",
    "className": "Editor",
    "classNameEventSourceRef": "ComboBoxEditor",
    "maximumSize": "500,350",
    "parent": "P94",
    "dataRow": "Einkaufsliste/MorPanTes-8R/morphpaneltest#1",
    "columnName": "TYPE_TYPEN",
    "enabled": true,
    "cellEditor": {
      "horizontalAlignment": 0,
      "verticalAlignment": 1,
      "preferredEditorMode": 0,
      "additionalCondition": null,
      "columnView": {
        "columnNames": [
          "TYPEN"
        ],
        "columnCount": 1,
        "rowDefinitions": []
      },
      "displayReferencedColumnName": null,
      "displayConcatMask": null,
      "linkReference": {
        "columnNames": [
          "TYPE_ID",
          "TYPE_TYPEN"
        ],
        "referencedColumnNames": [
          "ID",
          "TYPEN"
        ],
        "referencedDataBook": "Einkaufsliste/MorPanTes-8R/morphpaneltest.subStorages.typen#0"
      },
      "popupSize": {
        "width": 250,
        "height": 200
      },
      "searchColumnMapping": null,
      "searchTextAnywhere": true,
      "searchInAllTableColumns": false,
      "sortByColumnName": false,
      "tableHeaderVisible": false,
      "validationEnabled": true,
      "doNotClearColumnNames": null,
      "clearColumns": [
        "TYPE_ID",
        "TYPE_TYPEN"
      ],
      "additionalClearColumns": null,
      "className": "LinkedCellEditor",
      "tableReadonly": true,
      "directCellEditor": false,
      "autoOpenPopup": false
    },
    "eventFocusGained": true,
    "indexOf": 1,
    "cellEditor_editable_": true,
    "cellEditor_horizontalAlignment_": 0,
    "cellEditor_verticalAlignment_": 1,
    "constraints": "tm;lm;bm;r-2"
  }
]
```

**Comment by maximilianweidenauer** [comment]
Just saw your text and setup VisionX... Now it works!

**Comment by maximilianweidenauer** [comment]
The layout now updates as expected
