### ISSUE TITLE
Validator "Hide until first validate"

### ISSUE THREAD

**Issue by dun-zilla** [sibvisions/reactUI#59]
I configure my validators with the option “Hide until first validate”. Anyway, when I initially open a screen, the validators are visible.
When navigating through my records, the feature works as expecpted.

Opening the screen:
![20210201_1300 - Screenshot - TestApplication_-_Google_Chrome_173](https://user-images.githubusercontent.com/77725044/106456328-a537dc80-648d-11eb-838c-1eac88f0ff5b.png)

After navigating forward and backward again:
![20210201_1300 - Screenshot - TestApplication_-_Google_Chrome_174](https://user-images.githubusercontent.com/77725044/106456381-bc76ca00-648d-11eb-8213-7348a72a9d1d.png)

**Comment by rjahn** [comment]
Not sure if this isn't a problem on server-side... Have to check.

**Comment by maximilianweidenauer** [comment]
This problem doesn't occur anymore and thanks to the testing i did for this ticket right now, i fixed another layout bug!
