### ISSUE TITLE
Mini mode - hide menu

### ISSUE THREAD

**Issue by rolandhoermann** [sibvisions/reactUI#65]
In Mini / Smartphone mode the menu on the left side should not be shown. Instead, the menu should be supported via a hamburger menu.

**Comment by rjahn** [comment]
We already support hamburger menu? Any screenshots of your problem?

**Comment by rolandhoermann** [comment]
The menu on the left should be hidden and if you click on the 3 dashes = hamburger menu on the top, the menu should be displayed. Is there a control in prime react?

**Comment by rjahn** [comment]
No, there's no ready-made component.
Currently, the menu is collapsed and you can see a part of it. If you hover, it will move in...

We could introduce a property to hide it. But sometimes it's nice to have the menu visible.

**Comment by maximilianweidenauer** [comment]
Menu now supports a property "showMenuMini". If true, the behavoir is like it used to be (menu in mini mode is collapsed but visible). If false the menu is only visible when clicking the hamburger menu
