### ISSUE TITLE
Chart support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#66]
We changed our chart support in JVx and should support the same feature set in reactUI

**Comment by rjahn** [comment]
A demo screen: Chart Demo is now available in JVx.mobile project.

**Comment by rjahn** [comment]
Example:

```json
{
    "id" : "C132",
    "name" : "ChaDem-KY_C_data27",
    "className" : "Chart",
    "maximumSize" : "800,600",
    "yAxisTitle" : "Y Axis",
    "xAxisTitle" : "X Axis",
    "title" : "Title",
    "preferredSize" : "350,300",
    "minimumSize" : "16,16",
    "dataBook" : "JVxMobileDemo/ChaDem-KY/data#1",
    "xColumnName" : "TYP",
    "yColumnNames" : [ "Y1", "Y2", "Y3" ],
    "chartStyle" : 1002,
    "parent" : "P122",
    "eventFocusGained" : true,
    "yColumnLabels" : [ "Y1", "Y2", "Y3" ],
    "xColumnLabel" : "Typ",
    "indexOf" : 9,
    "constraints" : "t3;lm;b3;r0"
  }
```

chartStyle is the important property:

```java
    /** Style constant for showing a line chart. */
    public static final int STYLE_LINES = 0;
    /** Style constant for showing an area chart. */
    public static final int STYLE_AREA = 1;
    /** Style constant for showing a bar chart. */
    public static final int STYLE_BARS = 2;
    /** Style constant for showing a pie chart. */
    public static final int STYLE_PIE = 3;
    /** Style constant for showing an step line chart. */
    public static final int STYLE_STEPLINES = 100;
    /** Style constant for showing an area chart. */
    public static final int STYLE_STACKEDAREA = 101;
    /** Style constant for showing an area chart. */
    public static final int STYLE_STACKEDPERCENTAREA = 201;
    /** Style constant for showing a stacked bar chart. */
    public static final int STYLE_STACKEDBARS = 102;
    /** Style constant for showing a stacked bar chart. */
    public static final int STYLE_STACKEDPERCENTBARS = 202;
    /** Style constant for showing a overlapped bar chart. */
    public static final int STYLE_OVERLAPPEDBARS = 302;
    /** Style constant for showing a bar chart. */
    public static final int STYLE_HBARS = 1002;
    /** Style constant for showing a stacked bar chart. */
    public static final int STYLE_STACKEDHBARS = 1102;
    /** Style constant for showing a stacked bar chart. */
    public static final int STYLE_STACKEDPERCENTHBARS = 1202;
    /** Style constant for showing a overlapped bar chart. */
    public static final int STYLE_OVERLAPPEDHBARS = 1302;
    /** Style constant for showing a ring chart. */
    public static final int STYLE_RING = 103;
```

**Comment by gimmixAT** [comment]
any preferences yet on which library we should use to render the charts?

- https://d3js.org/ -> would be super flexible but we would probably have to implement chart types pretty much ourselves or copy & adapt some of the demos: https://observablehq.com/@d3/gallery
- https://www.chartjs.org -> would be a bit more chart focused and seems to cover most of the chartstyles above https://www.chartjs.org/samples/latest/, there is also a react wrapper we could try: https://github.com/reactchartjs/react-chartjs-2

**Comment by maximilianweidenauer** [comment]
When I first implemented the chart, i used the primereact chart component which basically uses chartjs. https://www.primefaces.org/primereact/showcase/#/chartdemo
There is not a lot of documentation on primereact, but afaik you can use all chartjs options.

**Comment by gimmixAT** [comment]
Mh the version of chartjs in prime seems to be a bit old but that should be a good startingpoint at least.  
In the worst case we can just write our own wrapper with a similar API and replace the prime one.

**Comment by rjahn** [comment]
We won't create a new charts binding. The existing prime react charts are okay.

* d3js is to complex and too much work
* Charts is great and currently we don't need the latest version.

And yes, if charts of prime react is too old, we could use this  as template for our own binding!

**Comment by gimmixAT** [comment]
Displaying the charts via chartjs is now mostly implemented. Most remaining aspects are cosmetic differences. Maybe you guys could have a look where we should do some additional tweaking.

There are still some remaining issues I'll need some input on:
- The fifth group on "category charts" is rendered as "Z" in swing but acutually labeled "E" in the data. Is this a bug or can that be overridden at some point?
- I can't figure out how to process the data to get the result from the "category charts" page. (Currently it's the sum)
![piechart](https://user-images.githubusercontent.com/1855152/114428990-26fa6380-9bbd-11eb-91cd-03bb74647eee.png)
![piechart_swing](https://user-images.githubusercontent.com/1855152/114428991-2792fa00-9bbd-11eb-9643-6b7496854990.png)

- Stacked areas look different in swing but are imho wrong there:
![stackedarea](https://user-images.githubusercontent.com/1855152/114428693-c9661700-9bbc-11eb-80ee-034a35cf7fa4.png)
![stackedarea_swing](https://user-images.githubusercontent.com/1855152/114428697-cb2fda80-9bbc-11eb-82e7-e4a5c679d44a.png)

**Comment by mhandsteiner** [comment]
1. Z is displayed instead of E, as there is a translation de: E en: Z
So all Labels and Categories have to be translated.

2. If a PIE Chart has set one Y column, the sum of every category stored in X Column is shown per Category. 
   If two or more Y Columns are set, only the values of the current selected row are shown for every column
   
3. The Percentage Area Chart is for some Reason broken in Swing.

A Question about the colors. You copied the Swing colors (They are nearby Swing default, but not very beautiful.) If the default colors of JsChart are better, we can probably use them in swing...

**Comment by mhandsteiner** [comment]
I checked the Percentage Area Chart again. Swing JFreeChart does not support the percentage mode for xy charts.
This is only supported by Vaadin (high charts) and by the jschart.

**Comment by mhandsteiner** [comment]
I've extracted the colors of vaadin charts.
In colors in vaadin have in some charts transparency of 0.75 in most charts they are solid without transparency.
Its not so easy there to have the same transparency in all chart types.

            new SolidColor(94,  144, 233), // #5E90E9
            new SolidColor(210, 110, 104), // #D26E68
            new SolidColor(172, 219, 108), // #ACDB6C
            new SolidColor(240, 221, 106), // #F0DD6A
            new SolidColor(126, 216, 211), // #7ED8D3
            new SolidColor(211, 111, 163), // #D36FA3
            new SolidColor(104,  95, 170), // #685FAA
            new SolidColor(228, 133,  80), // #E48550
            new SolidColor(70,   97, 140), // #46618C
            new SolidColor(152,  87,  80), // #985750
            new SolidColor(141, 173,  95), // #8DAD5F
            new SolidColor(181, 168, 102), // #B5A866
            new SolidColor(73,  119, 128), // #497780
            new SolidColor(133,  65, 110), // #85416E
            new SolidColor(82,   88, 162), // #5258A2
            new SolidColor(140,  92,  66)  // #8C5C42

![image](https://user-images.githubusercontent.com/43437457/115686015-12566200-a359-11eb-8807-a6ae94772793.png)

**Comment by gimmixAT** [comment]
Thanks for all the feedback. The Pie Chart should behave es expected now and the values display as percentages.
I also made the chart colors configurable via css variables so we can customize that easily.

**Comment by mhandsteiner** [comment]
Gauges have properties for 
minValue, maxValue, minWarningValue, maxWarningValue, minErrorValue, maxErrorValue.

The used colors for error, warning, ok are:

    /** Color for error value. */
    public static final SolidColor COLOR_ERROR      = new SolidColor("#DF5353");
    /** Color for warning value. */
    public static final SolidColor COLOR_WARNING    = new SolidColor("#DDDF0D");
    /** Color for ok value. */
    public static final SolidColor COLOR_OK         = new SolidColor("#55BF3B");

**Comment by maximilianweidenauer** [comment]
I guess this is done and can be closed
