### ISSUE TITLE
path aliases for better import paths

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#77]
path aliases are more useful `../../../frontmask` becomes `@frontmask`

**Comment by gimmixAT** [comment]
This is sadly a bit more involved with Create React App based projects and needs some additional modules
https://github.com/oklas/react-app-rewire-alias
https://github.com/timarney/react-app-rewired

**Comment by rjahn** [comment]
We should avoid too many dependencies!
