### ISSUE TITLE
Customizable login background

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#83]
needs to be discussed first!

**Comment by rjahn** [comment]
There's a mobile_style.xml and for mobile apps it's possible to configure background, title, ....
The style can be requested from the server.

We should support a different style for react UI. 

Also possible is that the server sends the background of desktop app....

Need some test.

**Comment by maximilianweidenauer** [comment]
This has been supported since "DesktopPanels" are supported, I just forgot to close this ticket.
