### ISSUE TITLE
Generally more Progresses

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#84]
Currently when stuff is loading, we don't show any indication, that something is going on in the background... e.g. login. After the user presses the login button, there is no indication, that the user actually pressed the button and the login is being sent/processed. Use more Progresses/Load Animations

**Comment by gimmixAT** [comment]
List of scenarios / screens where a progress indicator would be nice to have:
- [ ] Login
- [ ] During screen loading until layouting is done
- [ ] Editable Field / Table while value is saving

**Comment by rjahn** [comment]
Data manipulation in general - if server roundtrip is necessary

**Comment by rjahn** [comment]
Load animation or progress spinner are not really nice.
What about a progress bar at the end of the page at the beginning?

Locking the UI?

Some operations won't work if we do it during another call... e.g.change a field and change the row selection.

**Comment by gimmixAT** [comment]
yes, a youtube style pseudo progressbar at the top would probably be the best solution for navigation / screen changes. 
e.g. http://buunguyen.github.io/topbar/ + https://github.com/MoOx/react-topbar-progress-indicator

for editable field saving I'd opt for a spinner in the field itself and if that isn't feasible because auf prime react limitations maybe also the youtube style top bar.

**Comment by rjahn** [comment]
ok, we should try it out!

**Comment by maximilianweidenauer** [comment]
More Topbar improvements:
- topbar is too slim
- When a screen is layouting show (temporarly maybe we find something better) a white screen, if possible, and when the layouting is done switch to the layout. It is irratating to first see the components appear at the top left, and then them adjusting their position

**Comment by maximilianweidenauer** [comment]
All in all the topbar works fine and is now shown for most server round trips. Sometimes the components still appear at the top left and then adjust their position, but I'll add an extra ticket for this issue and close this one.
