### ISSUE TITLE
Date Picker styling

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#85]
The PrimeReact datepicker is too large, needs to be smaller and the font isn't the same as in the rest of the application, month, -year-picker way to small

**Comment by maximilianweidenauer** [comment]
DatePicker uses 100% width of the input field, we should maybe set it to a universal smaller width/height and then wait for feedback 
![image](https://user-images.githubusercontent.com/66732863/122347325-31810280-cf4a-11eb-9c8d-fb311155e7a0.png)

**Comment by maximilianweidenauer** [comment]
Also: focus outline/box-shadow needs to be extended so it covers the button aswell. Like in the linked editor

**Comment by rjahn** [comment]
Yes, don't use full width of editor!

**Comment by gimmixAT** [comment]
the style tweaks should be implemented now

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/123747730-9118cf80-d8b3-11eb-965d-9de40679c1bb.png)
I'm uploading the whole screen as a size reference. @rjahn is the size of the datepicker now ok or should it be even smaller?

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/123747887-ca513f80-d8b3-11eb-8ed6-7bd5cc9e1529.png)
When there is a timepicker as well it is obviously larger. What do you think?

**Comment by rjahn** [comment]
Generelly great. Please remove some padding px from the bottom area?
