### ISSUE TITLE
Gauge Support

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#89]
Currently Gauge components are not implemented, see the various types in swing

**Comment by maximilianweidenauer** [comment]
https://www.primefaces.org/showcase/ui/chart/metergauge.xhtml?jfwid=348ef 
PrimeFaces has a similiar Control but currently PrimeReact doesn't support gauges

**Comment by maximilianweidenauer** [comment]
https://srujithm.github.io/react-advanced-gauge-chart/
https://react-google-charts.com/gauge-chart
more possible libs

**Comment by gimmixAT** [comment]
Basic support is implemented. 
Colors for the ring & arc gauge are still missing
For speedometer & meter I did a quick experiment how we could implement our own simple svg based widget.

![gauges](https://user-images.githubusercontent.com/1855152/116422301-e6971880-a83f-11eb-86ee-b544f7dc5e9b.png)

**Comment by gimmixAT** [comment]
Gauges are mostly implemented now with a custom svg based speedometer style component. 
Please let me know if any features or aspects are still missing.

![gauges_2](https://user-images.githubusercontent.com/1855152/117119137-f065d200-ad91-11eb-803d-1f21171daded.png)

**Comment by rjahn** [comment]
Gauge 2 -> label behind the arrow (z-order)?

Vaadin UI looks a little bit different:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1307043/117121114-771bae80-ad94-11eb-9a2b-44c72e79336c.png">

Ring -> thicker, border

**Comment by rjahn** [comment]
open ring: labels missing left and right

**Comment by rjahn** [comment]
thick ring looks better

**Comment by gimmixAT** [comment]
gauges are now more like the vaadin ones

![gauges_3](https://user-images.githubusercontent.com/1855152/117162666-43a44880-adc3-11eb-9836-5edfbad76735.png)

**Comment by rjahn** [comment]
very nice.

**Comment by mhandsteiner** [comment]
superb
