### ISSUE TITLE
DirectCellEditor Support

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#92]
Currently direct Celleditors are not supported

**Comment by rjahn** [comment]
We have a rule on mobile flutter clients: If direct cell editor or preferredEditorMode 0, edit should be possible....

direct cell editors are checkbox, choice
others are editors like linked cell editor, but prefEditMode 0 (= single click) is not set automatically. It's a user-defined option.

Our flutter client opens a popup in this case, but our react UI should show the linked cell editor.

Editing a whole record is already possible direct in the table?

**Comment by maximilianweidenauer** [comment]
Editing a record directly in the table is possible via double click (text, linked etc), single click is currently only supported by checkbox and choice, preferredEditorMode and directCellEditor are currently not considered.

**Comment by rjahn** [comment]
prefEditMode = 1 means single click, 0 is double click
