### ISSUE TITLE
Refactoring DatePicker

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#93]
We maybe have to use another DatePicker because PrimeReact DatePicker ALWAYS, puts the time after the date (if time is enabled), which isn't desired. Currently I manipulate the value of the DatePicker to remove the time which isn't ideal at all, because it manipulates the DOM value directly and onChange, the PrimeReact time shortly flickers before it disappears

**Comment by gimmixAT** [comment]
**wip:** datepicker suggestions:
- https://reactdatepicker.com/
